import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/lib/cafe-db';
import { act,initialAdventure,publicAdventure,type Adventure } from '@/lib/adventure';
import { z } from 'zod';
export const dynamic='force-dynamic';
const actionSchema=z.object({requestId:z.string().uuid(),type:z.enum(['explore','recruit','leave','care','evolve','start-memory','flip','claim-quest']),habitat:z.string().max(30).optional(),creatureId:z.string().max(40).optional(),index:z.number().int().min(0).max(11).optional(),questId:z.string().max(40).optional()});
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function read(userId:string){const db=database();const row=await db.prepare('SELECT data,version FROM adventure_state WHERE user_id=?').bind(userId).first<{data:string;version:number}>();const progress=await db.prepare('SELECT coffees FROM creature_progress WHERE user_id=?').bind(userId).first<{coffees:number}>();return {state:row?JSON.parse(row.data) as Adventure:initialAdventure(),version:row?.version??0,coffeeTotal:progress?.coffees??0};}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return response({error:'Sign in to visit your companions.'},401);const {state,coffeeTotal}=await read(user.userId);return response(publicAdventure(state,coffeeTotal));}catch(e){console.error('Adventure load failed',e);return response({error:'Your adventure is resting for a moment. Please try again.'},503)}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return response({error:'Sign in to start your adventure.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return response({error:'Please play from your café.'},403);const parsed=actionSchema.safeParse(await req.json());if(!parsed.success)return response({error:'Please check your action.'},400);const action=parsed.data;const db=database();await db.prepare('INSERT OR IGNORE INTO adventure_state(user_id,data,version) VALUES (?,?,0)').bind(user.userId,JSON.stringify(initialAdventure())).run();const {state,version,coffeeTotal}=await read(user.userId);if(state.receipts.includes(action.requestId))return response({state:publicAdventure(state,coffeeTotal),message:'Already saved.'});let message:string;try{message=act(state,coffeeTotal,action,()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296);}catch(e){return response({error:e instanceof Error?e.message:'Choose another action.'},400)}state.receipts=[...state.receipts.slice(-49),action.requestId];const updated=await db.prepare('UPDATE adventure_state SET data=?,version=version+1 WHERE user_id=? AND version=?').bind(JSON.stringify(state),user.userId,version).run();if(!updated.meta.changes)return response({error:'Your adventure changed in another window. Please try again.'},409);return response({state:publicAdventure(state,coffeeTotal),message});}catch(e){console.error('Adventure action failed',e);return response({error:'That action couldn’t be saved. Please try again.'},503)}}
