import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database, photos } from '@/lib/cafe-db';
import { z } from 'zod';
import { creatureById } from '@/lib/creatures';
export const dynamic='force-dynamic';
const entrySchema=z.object({id:z.string().uuid(),kind:z.enum(['coffee','reflection']),title:z.string().trim().min(1).max(120),body:z.string().max(5000),mood:z.enum(['Peaceful','Grateful','Hopeful','Tired','Heavy-hearted']),drink:z.enum(['Latte','Cappuccino','Espresso','Cold brew','Pour-over','Other','']),prompt:z.string().max(300)}).refine(d=>d.kind==='coffee'?d.drink.length>0:d.body.trim().length>0);
const headers={'Cache-Control':'no-store'};
function json(data:unknown,status=200){return Response.json(data,{status,headers});}
function originOK(req:Request){const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin;}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to open your journal.'},401);const db=database();const entries=await db.prepare('SELECT id,kind,title,body,mood,drink,prompt,photo,created_at AS createdAt FROM moments WHERE user_id=? ORDER BY created_at DESC').bind(user.userId).all();const prefs=await db.prepare('SELECT palette,companion,plant,note FROM preferences WHERE user_id=?').bind(user.userId).first();const progress=await db.prepare('SELECT coffees FROM creature_progress WHERE user_id=?').bind(user.userId).first<{coffees:number}>();return json({coffeeTotal:progress?.coffees??0,entries:entries.results,prefs:prefs??{palette:'lavender',companion:'bean',plant:'yes',note:''}});}catch(e){console.error('Load café failed',e);return json({error:'Your journal is taking a moment. Please try again.'},503);}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save your moment.'},401);if(!originOK(req))return json({error:'Please save from your café.'},403);if(Number(req.headers.get('content-length')||0)>6*1024*1024)return json({error:'Choose a photo smaller than 5 MB.'},413);const form=await req.formData();const parsed=entrySchema.safeParse(JSON.parse(String(form.get('entry')||'{}')));if(!parsed.success)return json({error:'Please add a title and check your entry.'},400);const data=parsed.data;const db=database();const existing=await db.prepare('SELECT id FROM moments WHERE id=? AND user_id=?').bind(data.id,user.userId).first();if(existing)return json({id:data.id});let photoKey:null|string=null;const file=form.get('photo');if(file instanceof File && file.size){if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))return json({error:'Choose a JPG, PNG, or WebP photo smaller than 5 MB.'},400);photoKey=user.userId+'/'+data.id;await photos().put(photoKey,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});}
try{const insert=db.prepare('INSERT INTO moments (id,user_id,kind,title,body,mood,drink,prompt,photo,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(data.id,user.userId,data.kind,data.title,data.body,data.mood,data.drink,data.prompt,photoKey,new Date().toISOString());if(data.kind==='coffee'){await db.batch([insert,db.prepare('INSERT INTO creature_progress(user_id,coffees) VALUES (?,1) ON CONFLICT(user_id) DO UPDATE SET coffees=coffees+1').bind(user.userId)]);}else{await insert.run();}}catch(e){if(photoKey)await photos().delete(photoKey);throw e;}return json({id:data.id},201);
}catch(e){if(e instanceof SyntaxError)return json({error:'Please check your entry.'},400);console.error('Save moment failed',e);return json({error:'We couldn’t save that moment. Your draft is still here; please try again.'},503);}}
export async function PATCH(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to arrange your café.'},401);if(!originOK(req))return json({error:'Please save from your café.'},403);const data=z.object({palette:z.enum(['lavender','honey','forest']),companion:z.string().max(40),plant:z.enum(['yes','no']),note:z.string().max(1000)}).safeParse(await req.json());if(!data.success)return json({error:'Please check your café choices.'},400);const db=database();const p=data.data;const creature=creatureById(p.companion);const progress=await db.prepare('SELECT coffees FROM creature_progress WHERE user_id=?').bind(user.userId).first<{coffees:number}>();if(!creature||creature.at>(progress?.coffees??0))return json({error:'That companion hasn’t arrived yet.'},400);await db.prepare('INSERT INTO preferences(user_id,palette,companion,plant,note) VALUES (?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET palette=excluded.palette,companion=excluded.companion,plant=excluded.plant,note=excluded.note').bind(user.userId,p.palette,p.companion,p.plant,p.note).run();return json({ok:true});}catch(e){console.error('Save café failed',e);return json({error:'Your café couldn’t be saved. Please try again.'},503);}}
export async function DELETE(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Sign in to change your journal.'},401);if(!originOK(req))return json({error:'Please use your café to remove moments.'},403);const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'Choose a moment.'},400);const db=database();const row=await db.prepare('SELECT photo FROM moments WHERE id=? AND user_id=?').bind(id,user.userId).first<{photo:string|null}>();await db.prepare('DELETE FROM moments WHERE id=? AND user_id=?').bind(id,user.userId).run();if(row?.photo){try{await photos().delete(row.photo);}catch(e){console.error('Photo cleanup failed',e);}}return json({ok:true});}catch(e){console.error('Delete moment failed',e);return json({error:'That moment couldn’t be removed. Please try again.'},503);}}
