'use client';
import {useState} from 'react';
import {Compass,Cookie,Ticket,Star,Heart,Sparkles,Gift,Check,ArrowRight,Leaf,Flame,Cloud,Moon,Waves,Lightbulb,RotateCcw,Coffee,BookHeart} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {creatures,creatureById,type Creature} from '@/lib/creatures';
import {habitats,quests,questProgress,evolveTarget,bondNeeded,type PublicAdventure} from '@/lib/adventure';
export function CreatureArt({creature}:{creature:Creature}){return <div role="img" aria-label={creature.name} className="creature-art" style={{backgroundImage:`url(/roster-${creature.sheet}.webp)`,backgroundSize:`${creature.columns*100}% ${creature.rows*100}%`,backgroundPosition:`${(creature.cell%creature.columns)*100/(creature.columns-1)}% ${Math.floor(creature.cell/creature.columns)*100/(creature.rows-1)}%`,aspectRatio:creature.columns===4?'1':'1'}}/>}
export function MysteryArt(){return <div className="mystery-art" role="img" aria-label="Undiscovered Sipling"><Sparkles size={20}/><span>?</span><small>A little mystery</small></div>}
function MemoryFace({id}:{id:string}){const c=creatureById(id);if(c)return <CreatureArt creature={c}/>;const icons:Record<string,typeof Coffee>={coffee:Coffee,leaf:Leaf,star:Star,heart:Heart,moon:Moon,book:BookHeart};const key=id.replace('item:','');const Icon=icons[key]??Sparkles;return <div className="symbol-card"><Icon size={31}/><small>{key}</small></div>}
function memoryName(id:string){return creatureById(id)?.name??id.replace('item:','');}
export type AdventureAction={type:string;habitat?:string;creatureId?:string;index?:number;questId?:string};
export function AdventurePanel({state,act,busy,companion,onCollection}:{state:PublicAdventure|null;act:(a:AdventureAction)=>Promise<void>;busy:boolean;companion:Creature;onCollection:()=>void}){
 const [section,setSection]=useState('explore');
 const visitor=state?.encounter?creatureById(state.encounter.creatureId):null;
 const evolved=evolveTarget(companion.id);const bond=state?.bonds[companion.id]??0;const needed=bondNeeded(companion.id);const nextUnlocked=evolved&&state?.unlocked.includes(evolved.id);
 if(!state)return <div className="adventure-loading" role="status">Your adventure is getting ready. Sign in from Today if needed.</div>;
 const icons=[Leaf,Waves,Flame,Cloud,Lightbulb,Moon];
 return <div className="adventure"><div className="inventory" aria-label="Your adventure supplies"><span><Cookie/>{state.treats}<small>Treats</small></span><span><Ticket/>{state.tickets}<small>Trail tickets</small></span><span><Star/>{state.stars}<small>Stars</small></span></div><Tabs value={section} onValueChange={setSection}><TabsList className="adventure-tabs" aria-label="Adventure activities"><TabsTrigger value="explore"><Compass size={16}/>Explore</TabsTrigger><TabsTrigger value="care"><Heart size={16}/>Care</TabsTrigger><TabsTrigger value="play"><Sparkles size={16}/>Play</TabsTrigger><TabsTrigger value="quests"><Gift size={16}/>Quests</TabsTrigger></TabsList></Tabs>
 {section==='explore'&&<>{visitor?<section className="encounter"><span className="eyebrow">A LITTLE RUSTLE… A NEW FACE</span><div className="encounter-art"><CreatureArt creature={visitor}/><span className="encounter-spark spark-one">✧</span><span className="encounter-spark spark-two">✦</span></div><span className={'type-pill rarity-'+visitor.rarity.toLowerCase()}>{visitor.type} · {visitor.rarity}</span><h2>You met {visitor.name}!</h2><p>{visitor.stage===1||state.seen.includes(visitor.family.toLowerCase())||state.unlocked.includes(visitor.family.toLowerCase())?visitor.description:`A ${visitor.rarity.toLowerCase()} ${visitor.type.toLowerCase()} Sipling, with a little magic all its own. It looks curious about you.`}</p>{state.unlocked.includes(visitor.id)&&<p className="already-friend">An old friend! Sharing a treat grows your bond.</p>}<div className="encounter-actions"><button className="primary-button" disabled={busy||state.treats<visitor.stage} onClick={()=>act({type:'recruit'})}><Cookie size={17}/>Offer {visitor.stage} {visitor.stage===1?'treat':'treats'}</button><button className="secondary-button" disabled={busy} onClick={()=>act({type:'leave'})}>Wave goodbye</button></div>{state.treats<visitor.stage&&<button className="text-button" onClick={()=>setSection('play')}>Play a matching game for more treats <ArrowRight size={16}/></button>}</section>:<><div className="adventure-intro"><h2>Where shall we wander?</h2><p>One ticket opens a trail. Every visit brings a chance to meet someone new.</p></div><div className="habitat-grid">{habitats.map((h,i)=>{const Icon=icons[i];const residents=creatures.filter(c=>h.types.includes(c.type));return <button key={h.id} className={'habitat '+h.color} onClick={()=>act({type:'explore',habitat:h.id})} disabled={busy||state.tickets<1}><Icon size={30} strokeWidth={1.4}/><span className="habitat-preview">{[0,1,2].map(index=>{const c=residents.filter(c=>state.seen.includes(c.id)||state.unlocked.includes(c.id))[index];return c?<CreatureArt key={c.id} creature={c}/>:<MysteryArt key={index}/>})}</span><h3>{h.name}</h3><p>{h.subtitle}</p><span className="habitat-foot"><span>{residents.length} species</span><span><Ticket size={14}/> 1 ticket</span></span></button>})}</div>{state.tickets<1&&<div className="supply-note">Ready for another trail? <button onClick={()=>setSection('play')}>Play a matching game to earn tickets.</button></div>}<p className="collection-footnote">Familiar friends are common. Rare and Radiant encounters are special surprises. No purchases, timers, or lost streaks.</p></>}</>}
 {section==='care'&&<section className="care-panel"><div className="care-creature" key={companion.id+'-'+bond}><CreatureArt creature={companion}/><span className="eyebrow">YOUR CAFÉ SIPLING</span><h2>{companion.name}</h2><p>{companion.description}</p><button className="text-button" onClick={onCollection}>Choose another friend <ArrowRight size={16}/></button></div><div className="care-controls"><p className="eyebrow">A FRIENDSHIP THAT GROWS</p><h2>A little love goes a long way.</h2><div className="bond-heading"><span><Heart size={17}/>Your bond</span><strong>{bond}</strong></div><Progress value={evolved?Math.min(100,bond/needed*100):100} aria-label="Bond toward next evolution"/>{evolved?<p className="bond-description">{nextUnlocked?`${evolved.name} is already part of your collection.`:`Reach ${needed} bond to reveal the next evolution.`}</p>:<p className="bond-description">A fully evolved friend. There’s still plenty of love to share.</p>}<button className="primary-button" disabled={busy||state.treats<1} onClick={()=>act({type:'care',creatureId:companion.id})}><Cookie size={18}/>Share a treat <span>+3 bond</span></button>{evolved&&!nextUnlocked&&<button className="evolve-button" disabled={busy||bond<needed} onClick={()=>act({type:'evolve',creatureId:companion.id})}><Sparkles size={19}/>{bond>=needed?'Reveal the next evolution':`${needed-bond} bond until evolution`}</button>}<small>One treat per visit to the snack jar. Earlier forms stay in your collection.</small>{state.treats<1&&<button className="text-button" onClick={()=>setSection('play')}>Play for more treats <ArrowRight size={16}/></button>}</div></section>}
 {section==='play'&&<section className="memory-panel"><div className="game-heading"><div><p className="eyebrow">A LITTLE GAME OF GOOD COMPANY</p><h2>Perfect pairs</h2></div>{state.memory&&<span>{state.memory.matched.length/2} / 6 pairs · {state.memory.moves} moves</span>}</div><p>Find the matching friends. Finish a board to earn 3 treats, 2 trail tickets, and 2 stars.</p>{!state.memory?<div className="game-start"><Sparkles size={40}/><h3>A familiar face, twice.</h3><button className="primary-button" disabled={busy} onClick={()=>act({type:'start-memory'})}>Let’s play <ArrowRight size={17}/></button></div>:<><div className="memory-grid">{state.memory.cards.map((id,i)=><button key={i} className={'memory-card '+(id?'flipped ':'')+(state.memory!.matched.includes(i)?'matched':'')} aria-label={id?`${memoryName(id)}${state.memory!.matched.includes(i)?', matched':''}`:`Turn card ${i+1}`} disabled={busy||state.memory!.matched.includes(i)||state.memory!.complete||state.memory!.revealed.includes(i)} onClick={()=>act({type:'flip',index:i})}>{id?<MemoryFace id={id}/>:<span><Sparkles size={27}/><small>Sip &amp; Wonder</small></span>}</button>)}</div>{state.memory.complete?<div className="game-complete"><Check size={25}/><div><h3>Six lovely pairs!</h3><p>Your treats and tickets are ready.</p></div><button className="primary-button" disabled={busy} onClick={()=>act({type:'start-memory'})}><RotateCcw size={17}/>Play again</button></div>:<p className="memory-hint">{state.memory.revealed.length===2?'Not a match. Choose another face-down card to keep looking.':'Take your time. There’s no timer.'}</p>}</>}</section>}
 {section==='quests'&&<section className="quest-list"><div className="adventure-intro"><h2>Little adventures, lovely rewards.</h2><p>A few things to discover at your own pace.</p></div>{quests.map(q=>{const progress=Math.min(q.goal,questProgress(state,q.kind));const claimed=state.claimed.includes(q.id);return <article key={q.id} className={'quest-card '+(claimed?'complete':'')}><span className="quest-icon">{claimed?<Check/>:<Gift/>}</span><div><h3>{q.name}</h3><p>{q.detail}</p><Progress value={progress/q.goal*100} aria-label={q.name+' progress'}/><small>{progress} / {q.goal} · {q.reward}</small></div><button className="secondary-button" disabled={busy||claimed||progress<q.goal} onClick={()=>act({type:'claim-quest',questId:q.id})}>{claimed?'Collected':progress>=q.goal?'Collect reward':'In progress'}</button></article>})}</section>}
 </div>
}
