import { creatures,creatureById } from './creatures';
export const habitats=[
{id:'grove',name:'Sunlit Grove',subtitle:'Leafy friends & flowering giants',types:['Grove','Harvest','Earth'],color:'grove'},
{id:'pond',name:'Crystal Lagoon',subtitle:'Tidal wonders & frosty little faces',types:['Water','Frost','Crystal'],color:'pond'},
{id:'hearth',name:'Sugarwood Café',subtitle:'Pastry pals & wonderfully warm hearts',types:['Bakery','Cocoa','Coffee','Candy','Honey','Tea','Spice','Ember'],color:'hearth'},
{id:'sky',name:'Cloudtop Gardens',subtitle:'Thunder paws & soaring wings',types:['Sky','Storm','Sun','Melody','Cloud'],color:'sky'},
{id:'workshop',name:'Lantern Workshop',subtitle:'Clockwork wonders & paper magic',types:['Clockwork','Paper','Glow','Earth'],color:'workshop'},
{id:'dream',name:'Starlight Hollow',subtitle:'Moonlit mysteries & velvet dreams',types:['Dream','Moon','Star','Velvet'],color:'dream'}];
export type Memory={cards:string[];revealed:number[];matched:number[];moves:number;complete:boolean};
export type Adventure={treats:number;tickets:number;stars:number;discovered:string[];seen:string[];bonds:Record<string,number>;visits:Record<string,number>;explorations:number;gamesWon:number;careCount:number;evolutions:number;recruits:number;encounter:{creatureId:string;habitat:string}|null;memory:Memory|null;claimed:string[];receipts:string[]};
export type PublicAdventure=Omit<Adventure,'receipts'|'memory'>&{memory:(Omit<Memory,'cards'>&{cards:(string|null)[]})|null;unlocked:string[]};
export const quests=[{id:'first-friend',name:'A new face at the café',detail:'Welcome a Sipling you meet while exploring.',goal:1,reward:'3 treats + 1 trail ticket',treats:3,tickets:1,kind:'friends'},{id:'three-trails',name:'A curious little wanderer',detail:'Explore three times.',goal:3,reward:'4 treats + 2 trail tickets',treats:4,tickets:2,kind:'explorations'},{id:'good-company',name:'Made with love',detail:'Share five treats with Siplings.',goal:5,reward:'3 treats + 2 trail tickets',treats:3,tickets:2,kind:'care'},{id:'sharp-eyes',name:'A perfect little match',detail:'Finish two matching games.',goal:2,reward:'5 treats + 2 trail tickets',treats:5,tickets:2,kind:'games'},{id:'growing-up',name:'A little more magical',detail:'Help a Sipling evolve.',goal:1,reward:'6 treats + 3 trail tickets',treats:6,tickets:3,kind:'evolutions'}];
export function initialAdventure():Adventure{return {treats:5,tickets:3,stars:0,discovered:['bean'],seen:['bean'],bonds:{bean:0},visits:{},explorations:0,gamesWon:0,careCount:0,evolutions:0,recruits:0,encounter:null,memory:null,claimed:[],receipts:[]}}
export function unlockedCreatures(state:Adventure,coffeeTotal:number){return [...new Set([...state.discovered,...creatures.filter(c=>c.at<=coffeeTotal).map(c=>c.id)])]}
export function publicAdventure(state:Adventure,coffeeTotal:number):PublicAdventure{const {receipts,memory,...rest}=state;const known=new Set([...(state.seen??[]),...unlockedCreatures(state,coffeeTotal)]);const hiddenIds=memory?[...new Set(memory.cards.filter(id=>!id.startsWith('item:')&&!known.has(id)))]:[];const symbols=['coffee','leaf','star','heart','moon','book'];return{...rest,seen:[...known],unlocked:unlockedCreatures(state,coffeeTotal),memory:memory?{...memory,cards:memory.cards.map((id,i)=>memory.revealed.includes(i)||memory.matched.includes(i)?id.startsWith('item:')||known.has(id)?id:'item:'+symbols[hiddenIds.indexOf(id)%6]:null)}:null}}
export function questProgress(state:Pick<Adventure,'discovered'|'explorations'|'careCount'|'gamesWon'|'evolutions'|'recruits'>,kind:string){return kind==='friends'?(state.recruits??0):kind==='explorations'?state.explorations:kind==='care'?state.careCount:kind==='games'?state.gamesWon:state.evolutions}
export function evolveTarget(id:string){const c=creatureById(id);return c?creatures.find(n=>n.family===c.family&&n.stage===c.stage+1):undefined}
export function bondNeeded(id:string){return creatureById(id)?.stage===1?15:30}
export function act(state:Adventure,coffeeTotal:number,action:{type:string;habitat?:string;creatureId?:string;index?:number;questId?:string},random:()=>number=Math.random):string{
 const unlocked=unlockedCreatures(state,coffeeTotal);
 switch(action.type){
 case 'explore':{if(state.encounter)throw new Error('You already have a visitor waiting. Welcome them or wave goodbye first.');const habitat=habitats.find(h=>h.id===action.habitat);if(!habitat)throw new Error('Choose a trail.');if(state.tickets<1)throw new Error('Finish a matching game to earn more trail tickets.');const roll=random();const stage=roll<.7?1:roll<.95?2:3;const pool=creatures.filter(c=>habitat.types.includes(c.type)&&c.stage===stage);const visitor=pool[Math.floor(random()*pool.length)];state.tickets--;state.explorations++;state.visits[habitat.id]=(state.visits[habitat.id]??0)+1;state.seen=[...new Set([...(state.seen??['bean']),visitor.id])];state.encounter={creatureId:visitor.id,habitat:habitat.id};return `You found ${visitor.name}!`;}
 case 'recruit':{if(!state.encounter)throw new Error('Explore a trail to meet someone new.');const c=creatureById(state.encounter.creatureId)!;const cost=c.stage;if(state.treats<cost)throw new Error(`You need ${cost} treats. A matching game will help.`);state.treats-=cost;if(!state.discovered.includes(c.id)){state.discovered.push(c.id);state.recruits=(state.recruits??0)+1;}state.bonds[c.id]=(state.bonds[c.id]??0)+3;state.stars+=c.stage;state.encounter=null;return `${c.name} is happy to be your friend!`;}
 case 'leave':state.encounter=null;return 'A friendly wave, until next time.';
 case 'care':{const id=action.creatureId??'';if(!unlocked.includes(id))throw new Error('Meet this Sipling first.');if(state.treats<1)throw new Error('Finish a matching game to earn more treats.');state.treats--;state.bonds[id]=(state.bonds[id]??0)+3;state.careCount++;return `${creatureById(id)!.name} loved that treat. Bond +3!`;}
 case 'evolve':{const id=action.creatureId??'';if(!unlocked.includes(id))throw new Error('Meet this Sipling first.');const target=evolveTarget(id);if(!target)throw new Error('This Sipling has reached its final form.');if(unlocked.includes(target.id))throw new Error('This evolution is already in your collection.');if((state.bonds[id]??0)<bondNeeded(id))throw new Error('Grow your bond a little more first.');state.discovered.push(target.id);state.bonds[target.id]=0;state.evolutions++;state.stars+=5;return `${creatureById(id)!.name} helped you discover ${target.name}! Both friends stay in your collection.`;}
 case 'start-memory':{if(state.memory&&!state.memory.complete)throw new Error('Finish your current matching game first.');const pool=[...creatures.filter(c=>unlocked.includes(c.id))];for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}const faces=pool.slice(0,6).map(c=>c.id);for(const symbol of ['coffee','leaf','star','heart','moon','book'])if(faces.length<6)faces.push('item:'+symbol);const cards=faces.flatMap(id=>[id,id]);for(let i=cards.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}state.memory={cards,revealed:[],matched:[],moves:0,complete:false};return 'Find six matching pairs.';}
 case 'flip':{const game=state.memory;if(!game||game.complete)throw new Error('Start a new matching game.');const i=action.index;if(!Number.isInteger(i)||i!<0||i!>=game.cards.length)throw new Error('Choose a card.');if(game.revealed.length===2)game.revealed=[];if(game.matched.includes(i!)||game.revealed.includes(i!))throw new Error('Choose a face-down card.');game.revealed.push(i!);if(game.revealed.length===2){game.moves++;const [a,b]=game.revealed;if(game.cards[a]===game.cards[b]){game.matched.push(a,b);game.revealed=[];if(game.matched.length===12){game.complete=true;state.gamesWon++;state.treats+=3;state.tickets+=2;state.stars+=2;return 'All six pairs! +3 treats, +2 trail tickets, +2 stars.'}return 'A lovely match!'}}return 'Card turned.';}
 case 'claim-quest':{const q=quests.find(q=>q.id===action.questId);if(!q||state.claimed.includes(q.id))throw new Error('That reward has already been collected.');if(questProgress(state,q.kind)<q.goal)throw new Error('There’s a little more to discover first.');state.claimed.push(q.id);state.treats+=q.treats;state.tickets+=q.tickets;return 'A little reward for your adventure!';}
 default:throw new Error('Choose an adventure action.');
 }
}
