import { creatures,creatureById } from './creatures';
export const habitats=[
{id:'grove',name:'Sunlit Grove',subtitle:'Leafy friends & flowering giants',types:['Grove','Harvest','Earth'],color:'grove'},
{id:'pond',name:'Crystal Lagoon',subtitle:'Tidal wonders & frosty little faces',types:['Water','Frost','Crystal'],color:'pond'},
{id:'hearth',name:'Sugarwood Café',subtitle:'Pastry pals & wonderfully warm hearts',types:['Bakery','Cocoa','Coffee','Candy','Honey','Tea','Spice','Ember'],color:'hearth'},
{id:'sky',name:'Cloudtop Gardens',subtitle:'Thunder paws & soaring wings',types:['Sky','Storm','Sun','Melody','Cloud'],color:'sky'},
{id:'workshop',name:'Lantern Workshop',subtitle:'Clockwork wonders & paper magic',types:['Clockwork','Paper','Glow','Earth'],color:'workshop'},
{id:'dream',name:'Starlight Hollow',subtitle:'Moonlit mysteries & velvet dreams',types:['Dream','Moon','Star','Velvet'],color:'dream'}];
export type Memory={cards:string[];revealed:number[];matched:number[];moves:number;complete:boolean};
export type RiddleDifficulty='easy'|'medium'|'hard';
export type RiddleState={week:string;question:string;solved:boolean;difficulty:RiddleDifficulty|null};
export const DAILY_TREAT_LIMIT=8;
const riddleCreature=creatures.find(c=>c.at===1000000&&c.rarity!=='Legendary')?.id??'aerocrystal';
const legendaryCreatures=creatures.filter(c=>c.at===1000000&&c.rarity==='Legendary'&&c.stage<4).map(c=>c.id);
const riddles=[{question:'I have a face but no eyes, hands but no arms, and I keep your café moving. What am I?',answer:'clock'},{question:'I grow brighter when shared, but I never get smaller. What am I?',answer:'kindness'},{question:'I can be cracked, made, told, and played. What am I?',answer:'joke'}];
function dayKey(date=new Date()){return date.toISOString().slice(0,10)}
function weekKey(date=new Date()){const day=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));const thursday=new Date(day);thursday.setUTCDate(day.getUTCDate()-day.getUTCDay()+4);const yearStart=new Date(Date.UTC(thursday.getUTCFullYear(),0,1));return `${thursday.getUTCFullYear()}-${String(Math.ceil((((thursday.getTime()-yearStart.getTime())/86400000)+1)/7)).padStart(2,'0')}`}
function currentRiddle(){const week=weekKey();const index=(Number(week.slice(-2))-1)%riddles.length;return {week,...riddles[index]}}
export type Adventure={treats:number;tickets:number;stars:number;discovered:string[];seen:string[];bonds:Record<string,number>;visits:Record<string,number>;explorations:number;gamesWon:number;careCount:number;evolutions:number;recruits:number;journalEntries:number;reflections:number;photos:number;dailyLogins:number;weeklyLogins:number;lastLoginDate:string|null;lastLoginWeek:string|null;encounter:{creatureId:string;habitat:string}|null;memory:Memory|null;claimed:string[];receipts:string[];treatDate:string;dailyTreats:number;riddleWeek:string;riddleSolved:boolean;riddleDifficulty:RiddleDifficulty|null};
export type PublicAdventure=Omit<Adventure,'receipts'|'memory'>&{memory:(Omit<Memory,'cards'>&{cards:(string|null)[]})|null;unlocked:string[];riddle:{week:string;question:string;solved:boolean;difficulty:RiddleDifficulty|null}};
export const quests=[{id:'first-friend',name:'A new face at the café',detail:'Welcome a Sipling you meet while exploring.',goal:1,reward:'3 treats + 1 trail ticket',treats:3,tickets:1,kind:'friends'},{id:'three-trails',name:'A curious little wanderer',detail:'Explore three times.',goal:3,reward:'4 treats + 2 trail tickets',treats:4,tickets:2,kind:'explorations'},{id:'good-company',name:'Made with love',detail:'Share five treats with Siplings.',goal:5,reward:'3 treats + 2 trail tickets',treats:3,tickets:2,kind:'care'},{id:'sharp-eyes',name:'A perfect little match',detail:'Finish two matching games.',goal:2,reward:'5 treats + 2 trail tickets',treats:5,tickets:2,kind:'games'},{id:'growing-up',name:'A little more magical',detail:'Help a Sipling evolve.',goal:1,reward:'6 treats + 3 trail tickets',treats:6,tickets:3,kind:'evolutions'},{id:'trail-scholar',name:'Trail scholar',detail:'Explore six times and learn the rhythm of the habitats.',goal:6,reward:'4 treats + 2 stars',treats:4,tickets:0,kind:'explorations'},{id:'kindred-circle',name:'A kindred circle',detail:'Welcome four different Siplings into your collection.',goal:4,reward:'5 treats + 2 trail tickets',treats:5,tickets:2,kind:'friends'},{id:'riddle-keeper',name:'Keeper of curious questions',detail:'Solve a weekly riddle.',goal:1,reward:'3 treats + 3 stars',treats:3,tickets:0,kind:'riddles'},{id:'long-walk',name:'The long way round',detail:'Explore ten times. The rarest paths take patience.',goal:10,reward:'6 treats + 3 trail tickets',treats:6,tickets:3,kind:'explorations'},{id:'constellation',name:'A pocketful of stars',detail:'Earn twenty stars from brave adventures.',goal:20,reward:'5 treats + 4 trail tickets',treats:5,tickets:4,kind:'stars'},{id:'gentle-hands',name:'Gentle hands',detail:'Share twelve treats with your companions.',goal:12,reward:'6 treats + 3 trail tickets',treats:6,tickets:3,kind:'care'},{id:'many-welcome',name:'Many small hellos',detail:'Welcome eight different Siplings.',goal:8,reward:'7 treats + 4 trail tickets',treats:7,tickets:4,kind:'friends'},{id:'memory-lane',name:'Memory lane',detail:'Finish five matching games.',goal:5,reward:'7 treats + 3 stars',treats:7,tickets:0,kind:'games'},{id:'master-of-bonds',name:'Master of bonds',detail:'Help three Siplings evolve.',goal:3,reward:'8 treats + 5 trail tickets',treats:8,tickets:5,kind:'evolutions'}];
type Quest={id:string;name:string;detail:string;goal:number;reward:string;treats:number;tickets:number;kind:string};
function generatedQuest(id:string,name:string,detail:string,goal:number,kind:string):Quest{const treats=Math.min(8,2+goal%5);const tickets=goal%3===0?2:1;return {id,name,detail,goal,reward:`${treats} treats + ${tickets} trail ticket${tickets===1?'':'s'}`,treats,tickets,kind}}
const journalQuests=Array.from({length:40},(_,i)=>generatedQuest(`journal-${String(i+1).padStart(2,'0')}`,`A page worth keeping ${i+1}`,`Save ${i+1} journal entr${i===0?'y':'ies'} in your café.`,i+1,'journals'));
const reflectionQuests=Array.from({length:30},(_,i)=>generatedQuest(`reflect-${String(i+1).padStart(2,'0')}`,`A quiet thought ${i+1}`,`Write ${i+1} reflection${i===0?'':'s'} for the moments that matter.`,i+1,'reflections'));
const photoQuests=Array.from({length:25},(_,i)=>generatedQuest(`photo-${String(i+1).padStart(2,'0')}`,`Frame the moment ${i+1}`,`Keep ${i+1} journal moment${i===0?'':'s'} with a photo.`,i+1,'photos'));
const puzzleQuests=Array.from({length:20},(_,i)=>generatedQuest(`puzzle-${String(i+1).padStart(2,'0')}`,`Pattern finder ${i+1}`,`Complete ${i+1} matching puzzle${i===0?'':'s'}.`,i+1,'puzzles'));
const dailyLoginQuests=Array.from({length:15},(_,i)=>generatedQuest(`daily-${String(i+1).padStart(2,'0')}`,`A day at a time ${i+1}`,`Return on ${i+1} different day${i===0?'':'s'} to tend your café.`,i+1,'daily-logins'));
const weeklyLoginQuests=Array.from({length:10},(_,i)=>generatedQuest(`weekly-${String(i+1).padStart(2,'0')}`,`A week of wonder ${i+1}`,`Visit your café during ${i+1} different week${i===0?'':'s'}.`,i+1,'weekly-logins'));
const trailQuests=Array.from({length:10},(_,i)=>generatedQuest(`trail-${String(i+1).padStart(2,'0')}`,`One more little trail ${i+1}`,`Complete ${i+1} trail exploration${i===0?'':'s'} and see what turns up.`,i+1,'explorations'));
quests.push(...journalQuests,...reflectionQuests,...photoQuests,...puzzleQuests,...dailyLoginQuests,...weeklyLoginQuests,...trailQuests);
export function initialAdventure():Adventure{return {treats:5,tickets:3,stars:0,discovered:['bean'],seen:['bean'],bonds:{bean:0},visits:{},explorations:0,gamesWon:0,careCount:0,evolutions:0,recruits:0,journalEntries:0,reflections:0,photos:0,dailyLogins:0,weeklyLogins:0,lastLoginDate:null,lastLoginWeek:null,encounter:null,memory:null,claimed:[],receipts:[],treatDate:dayKey(),dailyTreats:0,riddleWeek:currentRiddle().week,riddleSolved:false,riddleDifficulty:null}}
export function unlockForTesting(state:Adventure){const ids=creatures.map(c=>c.id);state.discovered=[...new Set([...state.discovered,...ids])];state.seen=[...new Set([...state.seen,...ids])];state.bonds=Object.fromEntries(ids.map(id=>[id,100]));state.treats=Math.max(state.treats,100);state.tickets=Math.max(state.tickets,100);state.stars=Math.max(state.stars,100);state.explorations=Math.max(state.explorations,100);state.gamesWon=Math.max(state.gamesWon,100);state.careCount=Math.max(state.careCount,100);state.evolutions=Math.max(state.evolutions,100);state.recruits=Math.max(state.recruits,100);state.journalEntries=Math.max(state.journalEntries,100);state.reflections=Math.max(state.reflections,100);state.photos=Math.max(state.photos,100);state.dailyLogins=Math.max(state.dailyLogins,100);state.weeklyLogins=Math.max(state.weeklyLogins,100)}
function ensureCurrent(state:Adventure){const today=dayKey();if(state.treatDate!==today||!Number.isFinite(state.dailyTreats)){state.treatDate=today;state.dailyTreats=0}const riddle=currentRiddle();if(state.riddleWeek!==riddle.week){state.riddleWeek=riddle.week;state.riddleSolved=false;state.riddleDifficulty=null}}
export function recordLogin(state:Adventure,date=new Date()){ensureCurrent(state);const today=dayKey(date);const week=weekKey(date);if(state.lastLoginDate!==today){state.lastLoginDate=today;state.dailyLogins=(state.dailyLogins??0)+1}if(state.lastLoginWeek!==week){state.lastLoginWeek=week;state.weeklyLogins=(state.weeklyLogins??0)+1}}
export function recordJournal(state:Adventure,kind:'coffee'|'reflection',hasPhoto:boolean){state.journalEntries=(state.journalEntries??0)+1;if(kind==='reflection')state.reflections=(state.reflections??0)+1;if(hasPhoto)state.photos=(state.photos??0)+1}
function grantTreats(state:Adventure,amount:number){ensureCurrent(state);const granted=Math.max(0,Math.min(amount,DAILY_TREAT_LIMIT-state.dailyTreats));state.treats+=granted;state.dailyTreats+=granted;return granted}
export function unlockedCreatures(state:Adventure,coffeeTotal:number){return [...new Set([...state.discovered,...creatures.filter(c=>c.stage<4&&c.at<=coffeeTotal).map(c=>c.id)])]}
export function publicAdventure(state:Adventure,coffeeTotal:number):PublicAdventure{ensureCurrent(state);const {receipts,memory,...rest}=state;const known=new Set([...(state.seen??[]),...unlockedCreatures(state,coffeeTotal)]);const hiddenIds=memory?[...new Set(memory.cards.filter(id=>!id.startsWith('item:')&&!known.has(id)))]:[];const symbols=['coffee','leaf','star','heart','moon','book'];const riddle=currentRiddle();return{...rest,seen:[...known],unlocked:unlockedCreatures(state,coffeeTotal),riddle:{week:riddle.week,question:riddle.question,solved:state.riddleSolved,difficulty:state.riddleDifficulty},memory:memory?{...memory,cards:memory.cards.map((id,i)=>memory.revealed.includes(i)||memory.matched.includes(i)?id.startsWith('item:')||known.has(id)?id:'item:'+symbols[hiddenIds.indexOf(id)%6]:null)}:null}}
export function questProgress(state:Pick<Adventure,'discovered'|'explorations'|'careCount'|'gamesWon'|'evolutions'|'recruits'|'stars'|'journalEntries'|'reflections'|'photos'|'dailyLogins'|'weeklyLogins'> & {riddleSolved?:boolean},kind:string){return kind==='friends'?(state.recruits??0):kind==='explorations'?(state.explorations??0):kind==='care'?(state.careCount??0):kind==='games'||kind==='puzzles'?(state.gamesWon??0):kind==='evolutions'?(state.evolutions??0):kind==='stars'?(state.stars??0):kind==='journals'?(state.journalEntries??0):kind==='reflections'?(state.reflections??0):kind==='photos'?(state.photos??0):kind==='daily-logins'?(state.dailyLogins??0):kind==='weekly-logins'?(state.weeklyLogins??0):state.riddleSolved?1:0}
export function evolveTarget(id:string){const c=creatureById(id);return c?creatures.find(n=>n.family===c.family&&n.stage===c.stage+1):undefined}
export function bondNeeded(id:string){const stage=creatureById(id)?.stage;return !evolveTarget(id)?0:stage===1?18:stage===2?42:90}
export function act(state:Adventure,coffeeTotal:number,action:{type:string;habitat?:string;creatureId?:string;index?:number;questId?:string;answer?:string;difficulty?:RiddleDifficulty},random:()=>number=Math.random):string{
 ensureCurrent(state);
 const unlocked=unlockedCreatures(state,coffeeTotal);
 switch(action.type){
 case 'explore':{if(state.encounter)throw new Error('You already have a visitor waiting. Welcome them or wave goodbye first.');const habitat=habitats.find(h=>h.id===action.habitat);if(!habitat)throw new Error('Choose a trail.');if(state.tickets<1)throw new Error('Finish a matching game to earn more trail tickets.');const roll=random();const stage=roll<.7?1:roll<.95?2:3;const pool=creatures.filter(c=>habitat.types.includes(c.type)&&c.stage===stage);const legendary=pool.filter(c=>c.rarity==='Legendary');const ordinary=pool.filter(c=>c.rarity!=='Legendary');const encounterPool=legendary.length&&random()<.02?legendary:ordinary.length?ordinary:pool;const visitor=encounterPool[Math.floor(random()*encounterPool.length)];state.tickets--;state.explorations++;state.visits[habitat.id]=(state.visits[habitat.id]??0)+1;state.seen=[...new Set([...(state.seen??['bean']),visitor.id])];state.encounter={creatureId:visitor.id,habitat:habitat.id};return `You found ${visitor.name}!`;}
 case 'recruit':{if(!state.encounter)throw new Error('Explore a trail to meet someone new.');const c=creatureById(state.encounter.creatureId)!;const cost=c.stage;if(state.treats<cost)throw new Error(`You need ${cost} treats. A matching game will help.`);state.treats-=cost;if(!state.discovered.includes(c.id)){state.discovered.push(c.id);state.recruits=(state.recruits??0)+1;}state.bonds[c.id]=(state.bonds[c.id]??0)+3;state.stars+=c.stage;state.encounter=null;return `${c.name} is happy to be your friend. She is so loved.`;}
 case 'leave':state.encounter=null;return 'A friendly wave, until next time.';
 case 'care':{const id=action.creatureId??'';if(!unlocked.includes(id))throw new Error('Meet this Sipling first.');if(state.treats<1)throw new Error('Finish a matching game to earn more treats.');state.treats--;state.bonds[id]=(state.bonds[id]??0)+3;state.careCount++;return `${creatureById(id)!.name} loved that treat. You want to hold her close and be with her. Bond +3!`;}
 case 'evolve':{const id=action.creatureId??'';if(!unlocked.includes(id))throw new Error('Meet this Sipling first.');const target=evolveTarget(id);if(!target)throw new Error('This Sipling has reached its final form.');if(unlocked.includes(target.id))throw new Error('This evolution is already in your collection.');if((state.bonds[id]??0)<bondNeeded(id))throw new Error('Grow your bond a little more first.');state.discovered.push(target.id);state.bonds[target.id]=0;state.evolutions++;state.stars+=5;return `${creatureById(id)!.name} helped you discover ${target.name}! She is yours to love and keep close.`;}
 case 'start-memory':{if(state.memory&&!state.memory.complete)throw new Error('Finish your current matching game first.');const pool=[...creatures.filter(c=>unlocked.includes(c.id))];for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}const faces=pool.slice(0,6).map(c=>c.id);for(const symbol of ['coffee','leaf','star','heart','moon','book'])if(faces.length<6)faces.push('item:'+symbol);const cards=faces.flatMap(id=>[id,id]);for(let i=cards.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}state.memory={cards,revealed:[],matched:[],moves:0,complete:false};return 'Find six matching pairs.';}
 case 'flip':{const game=state.memory;if(!game||game.complete)throw new Error('Start a new matching game.');const i=action.index;if(!Number.isInteger(i)||i!<0||i!>=game.cards.length)throw new Error('Choose a card.');if(game.revealed.length===2)game.revealed=[];if(game.matched.includes(i!)||game.revealed.includes(i!))throw new Error('Choose a face-down card.');game.revealed.push(i!);if(game.revealed.length===2){game.moves++;const [a,b]=game.revealed;if(game.cards[a]===game.cards[b]){game.matched.push(a,b);game.revealed=[];if(game.matched.length===12){game.complete=true;state.gamesWon++;const treats=grantTreats(state,3);state.tickets+=2;state.stars+=2;return `All six pairs! +${treats} treats, +2 trail tickets, +2 stars.`}return 'A lovely match!'}}return 'Card turned.';}
 case 'solve-riddle':{const answer=action.answer?.trim().toLowerCase();const difficulty=action.difficulty;if(!['easy','medium','hard'].includes(difficulty??''))throw new Error('Choose a riddle difficulty.');if(state.riddleSolved)throw new Error('This week’s riddle is already solved.');if(answer!==currentRiddle().answer)throw new Error('Not quite. Read the clues and try again.');state.riddleSolved=true;state.riddleDifficulty=difficulty as RiddleDifficulty;const reward=difficulty==='easy'?1:difficulty==='medium'?3:5;const treats=grantTreats(state,reward);let message=`Correct! +${treats} treats`;if(difficulty==='medium'){state.tickets++;message+=' and +1 trail ticket'}if(difficulty==='hard'){state.stars+=3;message+=' and +3 stars';if(random()<.35){const candidate=legendaryCreatures.find(id=>!state.discovered.includes(id));if(candidate){state.discovered.push(candidate);state.seen=[...new Set([...state.seen,candidate])];state.bonds[candidate]=0;message+=` A legendary creature, ${creatureById(candidate)!.name}, answered your call!`}}}if(!state.discovered.includes(riddleCreature)){state.discovered.push(riddleCreature);state.seen=[...new Set([...state.seen,riddleCreature])];state.bonds[riddleCreature]=0;message+=` You unlocked ${creatureById(riddleCreature)!.name}!`}return message;}
 case 'claim-quest':{const q=quests.find(q=>q.id===action.questId);if(!q||state.claimed.includes(q.id))throw new Error('That reward has already been collected.');if(questProgress(state,q.kind)<q.goal)throw new Error('There’s a little more to discover first.');state.claimed.push(q.id);const treats=grantTreats(state,q.treats);state.tickets+=q.tickets;state.stars+=q.id==='trail-scholar'?2:q.id==='riddle-keeper'?3:0;return `A little reward for your adventure! +${treats} treats.`;}
 default:throw new Error('Choose an adventure action.');
 }
}
