import fourthEvolutions from './fourth-evolutions.json';
import wildDesigns from './wild-designs.json';
import expandedFamilies from './expanded-families.json';
import sirenForms from './emerald-siren.json';
export type CreatureStats={heart:number;warmth:number;curiosity:number;comfort:number;speed:number};
export type Creature = { id:string;name:string;family:string;type:string;secondaryType:string;stage:number;rarity:string;trait:string;stats:CreatureStats;at:number;sheet:number;cell:number;columns:number;rows:number;description:string;standaloneArt?:boolean };
export const stageNames=['Sprout','Awakened','Ascendant','Transcendent','Sovereign'];
export const stageSizes=['small','large','colossal','mythic','sovereign'];
export function stageName(stage:number){return stageNames[Math.max(0,Math.min(stage-1,stageNames.length-1))]??'Unknown'}
export function stageSize(stage:number){return stageSizes[Math.max(0,Math.min(stage-1,stageSizes.length-1))]??'unknown'}
function rarity(stage:number,index:number){return stage===0?'Familiar':stage===1?'Rare':index%4===0?'Legendary':'Exotic'}
const secondaryTypes=['Leaf','Mist','Stone','Tide','Song','Spark','Bloom','Velvet','Moon','Starlight','Spice','Dream'];
const traits=['Kindling Heart','Cloudstep','Steady Shell','Raincaller','Bright Chorus','Emberkeeper','Garden Gift','Velvet Welcome','Night Guide','Wishswimmer','Sugar Rush','Little Oracle'];
const midSurges=['grown noticeably bigger and bolder','doubled in size with a much stronger presence','filled out into a sturdier, more powerful shape','grown taller and considerably tougher','shed its tiny form for a bigger, steadier one','grown into a bigger, more confident shape crackling with new strength'];
const finalSurges=['towers over its first form, radiating a power it once could only dream of','has grown dramatically larger, its every move now carrying real weight','has become almost unrecognizable from its tiny first form, and unmistakably mightier','commands the room the moment it arrives, its presence bigger and bolder than ever','has grown into the biggest, strongest version of itself, full of hard-won power'];
const names=[['Bean','Mallow','Pebblit','Dewdrop','Mochirp','Cindlet','Spriggle','Whiskream','Duskwing','Glimfin','Bunbrew','Inkle'],['Fernox','Nimbus','Mossback','Bloomhop','Sonatina','Emberoot','Florabbit','Velvetail','Lunamoth','Astrakoi','Briohare','Inkwisp'],['Auroroot','Cloudora','Terrabloom','Lotusrain','Solaria','Cindrake','Verdantia','Royalwhisk','Noctilume','Galaxkoi','Cinnabun','Inkoracle']];
const types=['Grove','Cloud','Earth','Water','Melody','Ember','Grove','Velvet','Moon','Star','Bakery','Dream'];
const descriptions=[
 ['A brave little leaf fox. Collects fallen leaves and offers the prettiest one to a friend.','A cloud-soft dreamer with tiny crystal horns. Its sleepy eyes hold a little golden magic.','Carries a pebble garden everywhere. Moves slowly, but always shows up for its friends.','A pocket-sized frog who wears a lily as a hat. Loves the sound of rain on the café window.','A round mochi bird with a surprisingly big voice. Hums along with the coffee grinder.','A warm little salamander whose ember tail glows brighter when someone smiles.','A springy sprout rabbit. Plants tiny flowers in every footprint it leaves behind.','A cream-tufted kitten who curls around warm cups. Purrs like a very small espresso machine.','A shy moon moth who delivers dreams on velvet wings. Most at home in the evening light.','A little flying fish with starlit fins. Swims through steam as if it were an ocean.','A cinnamon-soft rabbit with floppy toasted ears. Gives excellent, slightly crumbly hugs.','A curious violet squid tucked into a teacup shell. Draws little hearts in the foam.'],
 ['Its leafy antlers glow in sunlight. Guides lost friends home through even the deepest woods.','A floating woolly ram who collects stray clouds. Makes the softest pillow in a thunderstorm.','An ancient-looking tortoise with a young tree on its back. A very patient listener.','A cheerful lotus-collared frog. Turns rainy afternoons into little pond-side concerts.','A bright crested songbird whose long tail keeps time with the music. Remembers every kind word.','A copper salamander with an ember frill. Keeps the café warm on the coldest evenings.','A flower-eared rabbit who tends a secret garden. Somehow always knows your favorite bloom.','A graceful cream cat with an impossibly long tail. Wraps it around anyone having a hard day.','A luminous moth with crescent-marked wings. Lights the path when the moon hides away.','A celestial koi who swims among the stars. Its scales shimmer like sunlight through water.','A golden brioche hare with magnificent toasted ears. Can smell a fresh pastry from miles away.','A gentle ink spirit whose ribbons float like calligraphy. Writes stories only dreams can read.'],
 ['A guardian fox with an aurora-bright leaf mane. Wherever it rests, the forest begins to bloom.','A cloud dragon with spiraling crystal horns. Fierce in flight, marshmallow-soft at heart.','A great stone turtle carrying a flowering sanctuary. Small Siplings travel safely in its garden.','A regal rain frog crowned with a lotus. Its flowing water cape brings life to sleeping gardens.','A radiant songbird with a rose-gold tail. Welcomes each morning with a song of new beginnings.','A copper dragon with spectacular ember wings. Uses its mighty breath to toast tiny pastries.','A majestic jade hare with flowering antlers. A gentle giant who makes room for everyone.','A celestial cream cat with a golden mane. Noble, brave, and completely defeated by a chin scratch.','A magnificent night moth with constellations on its wings. Makes the dark feel full of possibility.','A cosmic koi with swirling galaxy fins. Carries wishes through a quiet sea of stars.','A gloriously fluffy cinnamon rabbit. Legendary ears. Legendary hugs. Legendary appetite.','A wise floating cuttlefish with luminous stars. Sees the magic in the smallest ordinary things.']
];
const firstCreatures:Creature[]=names.flatMap((group,stage)=>group.map((name,cell)=>({id:name.toLowerCase(),name,family:names[0][cell],type:types[cell],secondaryType:secondaryTypes[cell],stage:stage+1,rarity:rarity(stage,cell),trait:traits[cell],stats:{heart:0,warmth:0,curiosity:0,comfort:0,speed:0},at:stage===0?(cell===0?0:cell===1?3:cell===2?1:cell===3?2:cell):stage===1?12+cell:27+cell*3,sheet:stage+1,cell,columns:4,rows:3,description:descriptions[stage][cell]})));
const extraCreatures:Creature[]=expandedFamilies.flatMap((family,index)=>family.names.map((name,stage)=>{const familyRarity=(family as {rarity?:string}).rarity;const creatureRarity=familyRarity??rarity(stage,index);return {standaloneArt:familyRarity==='Legendary',id:name.toLowerCase(),name,family:family.names[0],type:family.type,secondaryType:secondaryTypes[index%secondaryTypes.length],stage:stage+1,rarity:creatureRarity,trait:traits[index%traits.length],stats:{heart:0,warmth:0,curiosity:0,comfort:0,speed:0},at:1000000,sheet:4+Math.floor(index/30)*3+stage,cell:index%30,columns:5,rows:6,description:stage===0?`Meet ${name}: ${family.visual}. Curious, affectionate, and ready for a first little adventure.`:stage===1?`${name} has ${midSurges[index%midSurges.length]} since its first days as ${family.visual}. Its stance is bolder, its presence bigger, and its spirit even more playful.`:`The ${creatureRarity.toLowerCase()} final form of the ${family.names[0]} family. ${name} ${finalSurges[index%finalSurges.length]} — a dramatically bigger, more powerful evolution of the tiny ${family.visual} it once was.`}}));
const wildRoots=['Aero','Bramble','Cinder','Dapple','Echo','Fable','Glimmer','Hush','Ivy','Jumble','Kettle','Lumen','Mirth','Nova'];
const wildThemes=['crystal','moss','velvet','thunder','bubble','comet','marble'];
const wildTypes=['Grove','Ember','Cloud','Dream','Crystal','Storm','Bakery','Moon','Earth','Melody','Water','Velvet'];
const wildCreatures:Creature[]=wildRoots.flatMap((root,rootIndex)=>wildThemes.map((theme,themeIndex)=>{const index=90+rootIndex*wildThemes.length+themeIndex;const seed=`${root}${theme}`;const familyName=`${seed}kin`;const familyIndex=rootIndex*wildThemes.length+themeIndex;const group=familyIndex%3;const cell=familyIndex%30;const sheetFor=(stage:number)=>4+group*3+stage;return [
 {id:`${seed}kin`.toLowerCase(),name:familyName,family:familyName,type:wildTypes[index%wildTypes.length],secondaryType:secondaryTypes[index%secondaryTypes.length],stage:1,rarity:'Familiar',trait:traits[index%traits.length],stats:{heart:0,warmth:0,curiosity:0,comfort:0,speed:0},at:1000000,sheet:sheetFor(0),cell,columns:5,rows:6,description:`A curious ${theme}-touched companion born from ${root.toLowerCase()} winds. It collects odd little treasures and follows kind voices.`},
 {id:`${seed}rix`.toLowerCase(),name:`${seed}rix`,family:familyName,type:wildTypes[index%wildTypes.length],secondaryType:secondaryTypes[(index+3)%secondaryTypes.length],stage:2,rarity:'Rare',trait:traits[(index+3)%traits.length],stats:{heart:0,warmth:0,curiosity:0,comfort:0,speed:0},at:1000000,sheet:sheetFor(1),cell,columns:5,rows:6,description:`The ${familyName} has ${midSurges[index%midSurges.length]}, now a ${theme}-bright trickster crackling with ${root.toLowerCase()} energy. Its strange new talent makes every visit feel different — and considerably more powerful.`},
 {id:`${seed}ora`.toLowerCase(),name:`${seed}ora`,family:familyName,type:wildTypes[index%wildTypes.length],secondaryType:secondaryTypes[(index+6)%secondaryTypes.length],stage:3,rarity:index%4===0?'Legendary':'Exotic',trait:traits[(index+6)%traits.length],stats:{heart:0,warmth:0,curiosity:0,comfort:0,speed:0},at:1000000,sheet:sheetFor(2),cell,columns:5,rows:6,description:`A wildly unique, dramatically larger final form: ${seed}ora bends ${theme} light around its ${root.toLowerCase()} spirit and ${finalSurges[index%finalSurges.length]}. No two feel quite alike, even within the same family.`}
]})).flat();
function enrich(creature:Creature,index:number):Creature{const surge=creature.stage===1?1:creature.stage===2?1.65:creature.stage===3?2.5:3.75;const bonus=creature.rarity==='Legendary'?45:creature.rarity==='Exotic'?10:creature.rarity==='Rare'?5:0;const stats={heart:Math.round(45*surge)+bonus+(index*7)%18,warmth:Math.round(42*surge)+bonus+(index*5)%20,curiosity:Math.round(40*surge)+bonus+(index*3)%24,comfort:Math.round(44*surge)+bonus+(index*9)%17,speed:Math.round(38*surge)+bonus+(index*11)%19};return{...creature,stats,description:`${creature.description} ${creature.type} / ${creature.secondaryType} types. Signature trait: ${creature.trait}. It has ${stats.heart} heart, ${stats.warmth} warmth, ${stats.curiosity} curiosity, ${stats.comfort} comfort, and ${stats.speed} quickness.`}}
const baseCreatures:Creature[]=[...firstCreatures,...extraCreatures,...wildCreatures.map(c=>({...c,standaloneArt:true,description:wildDesigns[c.id as keyof typeof wildDesigns]}))].map(enrich);
export function creatureById(id:string){return creatures.find(c=>c.id===id)}

// Append fourth forms so existing collection numbers and saved IDs remain stable.
const transcendentCreatures:Creature[]=fourthEvolutions.map((form,index)=>{
 const previous=baseCreatures.find(c=>c.id===form.predecessor);
 if(!previous||previous.stage!==3)throw new Error('Fourth evolution requires a third-stage predecessor: '+form.predecessor);
 return enrich({...previous,id:form.id,name:form.name,stage:4,standaloneArt:true,description:form.description},baseCreatures.length+index);
});
// Append the only five-tier family without renumbering existing Siplings.
const sirenCreatures:Creature[]=sirenForms.map((form,index)=>({
 id:form.id,name:form.name,family:'Sirenbean',type:'Coffee',secondaryType:'Tide',
 stage:index+1,rarity:'Legendary',trait:'Beyond Rare',standaloneArt:true,
 stats:index===4?{heart:999,warmth:999,curiosity:999,comfort:999,speed:999}:{heart:65*(index+1),warmth:60*(index+1),curiosity:55*(index+1),comfort:62*(index+1),speed:50*(index+1)},
 at:1000000,sheet:0,cell:0,columns:1,rows:1,
 description:form.description+' The only mermaid Sipling family, with five tiers of wonder. Coffee / Tide types. Signature trait: Beyond Rare. Sirenbean has a 1% encounter chance per Sugarwood Café exploration; later forms require bonding.'
}));
export const creatures:Creature[]=[...baseCreatures,...transcendentCreatures,...sirenCreatures];
export function isEvolutionOnly(c:Creature){return c.stage>=4||(c.family==='Sirenbean'&&c.stage>1);}
export function familyStageCount(family:string){return Math.max(...creatures.filter(c=>c.family===family).map(c=>c.stage));}
