export type NoteProgress = { coffees: number; friends: number; explorations: number; evolutions: number; care: number; games: number };
export type LittleNote = { id: string; title: string; message: string };
export const milestones: (LittleNote & { metric: keyof NoteProgress; at: number })[] = [
  { id:'coffee-1',metric:'coffees',at:1,title:'Your first little ritual',message:'A warm cup, a little pause, and a memory worth keeping. Here’s to many cozy moments, Marissa.' },
  { id:'coffee-10',metric:'coffees',at:10,title:'A cup full of memories',message:'Ten coffee moments tucked away. The ordinary little things can become the sweetest memories.' },
  { id:'coffee-30',metric:'coffees',at:30,title:'Your cozy corner is growing',message:'Thirty little pauses. I hope this café keeps giving you a soft place to land, Marissa.' },
  { id:'friends-5',metric:'friends',at:5,title:'A tiny welcoming committee',message:'Five Siplings have found their way to you. They’ve clearly heard you’re excellent company.' },
  { id:'friends-25',metric:'friends',at:25,title:'Quite the little gathering',message:'Twenty-five friends! Someone should probably put another pot of coffee on.' },
  { id:'friends-100',metric:'friends',at:100,title:'A hundred little wonders',message:'A hundred Siplings, and still so much wonder ahead. Your curiosity makes this little world come alive.' },
  { id:'friends-300',metric:'friends',at:300,title:'Look at all this wonder',message:'Three hundred friends. Somewhere in this café, a tiny Sipling is trying to organize a very large group hug.' },
  { id:'friends-600',metric:'friends',at:600,title:'Every little friend, found',message:'All six hundred Siplings are home. What a beautiful little world you’ve made, Marissa.' },
  { id:'explore-1',metric:'explorations',at:1,title:'A little brave beginning',message:'One small adventure can lead to something lovely. I’m glad you took that first step, Marissa.' },
  { id:'explore-20',metric:'explorations',at:20,title:'A heart for adventure',message:'Twenty adventures later, there’s still magic around the next corner. Take your curiosity with you.' },
  { id:'evolve-1',metric:'evolutions',at:1,title:'Small beginnings, big wonder',message:'That tiny friend had something magnificent inside all along. Growing into something new takes a little care.' },
  { id:'evolve-10',metric:'evolutions',at:10,title:'Look how far they’ve grown',message:'Ten transformations, each its own kind of wonderful. Thank you for giving little things room to grow.' },
  { id:'care-5',metric:'care',at:5,title:'Kindness looks good on you',message:'Five little acts of care. Your Siplings appreciate every one—and probably have a few crumbs on their faces to prove it.' },
  { id:'game-1',metric:'games',at:1,title:'A tiny victory dance',message:'Your first memory-game win deserves a happy little wiggle. The Siplings are already doing theirs.' },
  {"id": "coffee-3", "metric": "coffees", "at": 3, "title": "Three cozy moments", "message": "Three cups remembered, three little pauses made yours. The café is learning your kind of cozy."},
  {"id": "coffee-5", "metric": "coffees", "at": 5, "title": "Your favorite little ritual", "message": "Five coffee memories! A Sipling is preparing a loyalty card with a paw print in every square."},
  {"id": "coffee-20", "metric": "coffees", "at": 20, "title": "Twenty sips of your story", "message": "Twenty coffee moments saved. May there be a happy little memory tucked into your next cup too."},
  {"id": "coffee-50", "metric": "coffees", "at": 50, "title": "Fifty warm little pauses", "message": "Fifty coffee memories belong to this café now. That is a lovely collection of ordinary moments, Marissa."},
  {"id": "coffee-100", "metric": "coffees", "at": 100, "title": "A hundred cups of cozy", "message": "One hundred coffee moments! The imaginary barista is polishing your very special imaginary mug."},
  {"id": "friends-10", "metric": "friends", "at": 10, "title": "Ten tiny personalities", "message": "Ten Siplings have joined your world. The group photo includes at least one enthusiastic blur."},
  {"id": "friends-50", "metric": "friends", "at": 50, "title": "A wonderfully full table", "message": "Fifty friends! Someone has started a seating chart. Someone else has eaten the corner of it."},
  {"id": "friends-150", "metric": "friends", "at": 150, "title": "So many little hellos", "message": "A hundred and fifty Siplings found. That is a lot of tiny faces happy to see you."},
  {"id": "friends-200", "metric": "friends", "at": 200, "title": "A whole neighborhood of wonder", "message": "Two hundred little friends! Your café is beginning to need its own very small town square."},
  {"id": "friends-400", "metric": "friends", "at": 400, "title": "Four hundred reasons to smile", "message": "Four hundred Siplings! Every little face adds something different to the world you’re discovering."},
  {"id": "friends-500", "metric": "friends", "at": 500, "title": "An extraordinary gathering", "message": "Five hundred friends found. The welcome party now requires several cakes and a rather ambitious banner."},
  {"id": "explore-5", "metric": "explorations", "at": 5, "title": "Getting your paws dusty", "message": "Five adventures! A little dust on your shoes and a little more wonder in your world."},
  {"id": "explore-10", "metric": "explorations", "at": 10, "title": "A happy little wanderer", "message": "Ten trips into the unknown. Your curiosity has excellent taste in adventures."},
  {"id": "explore-50", "metric": "explorations", "at": 50, "title": "Fifty paths wandered", "message": "Fifty adventures behind you. I hope the next little trail holds something that makes you grin."},
  {"id": "explore-100", "metric": "explorations", "at": 100, "title": "A well-traveled heart", "message": "One hundred explorations! Your imaginary travel journal is full of paw prints and very excited punctuation."},
  {"id": "explore-250", "metric": "explorations", "at": 250, "title": "A world you keep discovering", "message": "Two hundred and fifty adventures. There is something lovely about continuing to look for wonder."},
  {"id": "evolve-3", "metric": "evolutions", "at": 3, "title": "A little growing circle", "message": "Three evolutions! Tiny beginnings keep turning into magnificent surprises around here."},
  {"id": "evolve-5", "metric": "evolutions", "at": 5, "title": "Five wonderful transformations", "message": "Five Siplings have grown into new forms. Some of them may now need a larger café chair."},
  {"id": "evolve-25", "metric": "evolutions", "at": 25, "title": "From tiny paws to mighty friends", "message": "Twenty-five evolutions. Your café contains an impressive amount of power and an equally impressive need for snacks."},
  {"id": "evolve-50", "metric": "evolutions", "at": 50, "title": "Magnificent things take care", "message": "Fifty transformations! All that growing has made this little world wonderfully unexpected."},
  {"id": "care-15", "metric": "care", "at": 15, "title": "A little kindness adds up", "message": "Fifteen acts of care. Small kindnesses are becoming a lovely habit in your café."},
  {"id": "care-50", "metric": "care", "at": 50, "title": "A café full of care", "message": "Fifty caring moments! Your Siplings would like to return the favor with a slightly chaotic cuddle pile."},
  {"id": "care-100", "metric": "care", "at": 100, "title": "A hundred gentle gestures", "message": "One hundred acts of care. Every little friend deserves to feel looked after, and so do you, Marissa."},
  {"id": "game-5", "metric": "games", "at": 5, "title": "Five happy victory wiggles", "message": "Five memory-game wins! The Siplings are developing a victory dance with far too many spins."},
  {"id": "game-15", "metric": "games", "at": 15, "title": "A lovely little winning collection", "message": "Fifteen memory-game wins. Your tiny cheering section has worn out one set of imaginary pom-poms."},
  {"id": "game-50", "metric": "games", "at": 50, "title": "Fifty reasons for confetti", "message": "Fifty memory-game wins! The café is celebrating with petal confetti and a well-deserved imaginary cookie."},
];
export const surpriseNotes: LittleNote[] = [
  ['made-for-you','Just for you, Marissa','This little world was made to bring you a smile. I hope it finds you at just the right moment.'],
  ['warmth','A pocket of warmth','May your coffee be lovely, your shoulders feel lighter, and your day have a little unexpected goodness in it.'],
  ['bean','An important café update','A Sipling has appointed itself your official cheerleader. It is very small, very determined, and entirely on your side.'],
  ['rest','Permission to pause','You don’t have to earn a quiet moment. Take a breath, settle in, and let this one be yours.'],
  ['faith','A gentle wish','May you feel loved and held today, Marissa. There is room here for your hopes, your prayers, and your quiet moments.'],
  ['tiny','Something lovely','A little kindness. A warm mug. A very round Sipling. Sometimes joy arrives in the smallest packages.'],
  ['enough','For an ordinary day','You don’t have to make today extraordinary to find something beautiful in it.'],
  ['coffee','The café is on your side','Your imaginary coffee is always the perfect temperature. Your tiny friends are always happy you’re here.'],
  ['wonder','Keep a little wonder','I hope something makes you smile today—the kind of smile that sneaks up on you.'],
  ['grace','A little grace','Some days bloom slowly. Be gentle with yourself while yours unfolds.'],
  ['welcome','A familiar little place','Welcome back to your soft little corner of the world, Marissa. There’s always a place for you here.'],
  ['secret','A tiny secret','The Siplings held a meeting. The agenda was snacks. They also agreed that you’re pretty wonderful.'],
  ["surprise-013", "A small delivery", "A Sipling left a tiny flower by your cup. It took three trips to carry it, so please act surprised."],
  ["surprise-014", "Foam forecast", "Today’s forecast: a chance of fluffy clouds, warm coffee, and one extremely enthusiastic little friend."],
  ["surprise-015", "Reserved seating", "The comfiest chair in the café has your name on it, Marissa. The Siplings checked twice."],
  ["surprise-016", "Pocket sunshine", "Here’s a little sunshine for your pocket. Save it for a moment that could use some warmth."],
  ["surprise-017", "The biscuit committee", "The biscuit committee would like you to know that broken cookies still count as excellent cookies."],
  ["surprise-018", "Soft landing", "Whatever kind of day brought you here, you can set it down for a little while."],
  ["surprise-019", "A very small parade", "A parade in your honor is forming behind the sugar bowl. Progress is slow. Everyone has tiny legs."],
  ["surprise-020", "No rush, lovely", "Your cup doesn’t have a deadline. Neither does this little moment of peace."],
  ["surprise-021", "Window seat wishes", "May your next quiet moment feel like sunshine through a café window."],
  ["surprise-022", "The official verdict", "The Siplings reviewed the evidence. You deserve something nice today. Their report includes a doodle of a heart."],
  ["surprise-023", "Tiny paws, big plans", "Someone with very tiny paws is planning to make your day better. Step one appears to be waving at you."],
  ["surprise-024", "A little room to breathe", "Let your shoulders fall a little. There you go. There’s room to breathe here."],
  ["surprise-025", "Extra sweetness", "Your imaginary barista added an extra sprinkle of kindness. It’s the house specialty."],
  ["surprise-026", "A soft reminder", "Marissa, you’re allowed to enjoy a good moment without figuring out what comes next."],
  ["surprise-027", "A flower for your thoughts", "If your thoughts are busy, picture a little flower growing beside them. It doesn’t need to hurry either."],
  ["surprise-028", "The napkin artist", "A Sipling drew you a masterpiece on a napkin. It might be a heart. It might be a potato. The affection is clear."],
  ["surprise-029", "A lovely little detour", "Sometimes the best part of the day is the small, happy detour you didn’t plan."],
  ["surprise-030", "Steeped in kindness", "May a little kindness find its way into everything you do today, including how you speak to yourself."],
  ["surprise-031", "Your tiny fan club", "Your fan club has assembled. Attendance is excellent. One member fell asleep in a teacup."],
  ["surprise-032", "Nothing to prove", "You can simply be Marissa here. That’s more than enough for this little café."],
  ["surprise-033", "A quiet amen", "May a quiet moment of prayer leave a little more peace in your heart today."],
  ["surprise-034", "The marshmallow incident", "A Sipling tried to hug a marshmallow. We have decided this counts as a perfectly reasonable afternoon."],
  ["surprise-035", "Take the scenic sip", "There’s no prize for finishing your imaginary coffee quickly. Take the scenic sip."],
  ["surprise-036", "A tiny bouquet", "Someone gathered a bouquet just for you. It contains a daisy, a leaf, and a very promising twig."],
  ["surprise-037", "Goodness can be small", "A kind word can be small enough to fit in a moment and still stay with you all day."],
  ["surprise-038", "A cozy plot twist", "Perhaps something lovely is waiting in a part of today you haven’t reached yet."],
  ["surprise-039", "Little lantern", "May your faith be a little lantern when the path ahead feels hard to see."],
  ["surprise-040", "The sugar bowl lookout", "A Sipling is watching for your smile from the sugar bowl. It has packed snacks for the mission."],
  ["surprise-041", "Gentle company", "You don’t need to fill the silence. Sometimes gentle company is enough."],
  ["surprise-042", "A tiny toast", "Here’s to warm mugs, good company, and remembering where you put your coffee before it gets cold."],
  ["surprise-043", "The blanket inspector", "A very serious Sipling has inspected the café blankets. Its professional recommendation is to get cozy."],
  ["surprise-044", "A place for your hopes", "Bring your hopes, even the ones you don’t have words for yet. There’s space for them here."],
  ["surprise-045", "Sprinkles of joy", "If joy came in a shaker, the Siplings would absolutely forget to put the lid back on."],
  ["surprise-046", "A bright little thing", "I hope you notice one bright little thing today and let yourself enjoy it fully."],
  ["surprise-047", "Rest is welcome", "Even the café’s most adventurous Sipling takes naps. Sometimes right in the middle of an important sentence."],
  ["surprise-048", "A heart at ease", "May your heart find a little ease between everything you’re carrying today."],
  ["surprise-049", "A sip of silliness", "A Sipling ordered a cappuccino the size of its entire body. We admire the ambition."],
  ["surprise-050", "Come as you are", "Messy day or lovely day, you can come as you are. The café doesn’t require a polished entrance."],
  ["surprise-051", "A prayer-sized pause", "A breath, a hope, a few honest words. Your quiet moments of faith can be simple."],
  ["surprise-052", "Tiny applause", "If you hear a faint pattering, that’s the Siplings applauding you with their very small paws."],
  ["surprise-053", "The cozy department", "The cozy department has approved an extra moment of doing absolutely nothing."],
  ["surprise-054", "A little courage", "You don’t have to feel fearless to take a small step. Tiny paws take brave steps too."],
  ["surprise-055", "Your table is ready", "Marissa, your table is ready. The flowers are slightly crooked because a Sipling arranged them with great enthusiasm."],
  ["surprise-056", "A pleasant surprise", "May something sweet catch you off guard today, like finding a cookie you forgot you saved."],
  ["surprise-057", "Moonlight manners", "The moon doesn’t rush to be full. You can let your own growing take its time."],
  ["surprise-058", "A fragrant little thought", "Imagine the smell of fresh coffee and a warm pastry. That’s the mood this note is trying to bring you."],
  ["surprise-059", "A little kindness returned", "I hope some of the kindness you put into the world finds its way back to you today."],
  ["surprise-060", "A very fluffy assistant", "Your fluffy assistant is ready to help. It can offer moral support and sit on exactly the paper you need."],
  ["surprise-061", "A softer pace", "The world can move quickly. This little café is happy to move at your pace."],
  ["surprise-062", "A hopeful morning", "May a small hope stay with you today, even if it’s just the promise of a peaceful cup later."],
  ["surprise-063", "Café confetti", "The Siplings made confetti out of fallen petals. Cleanup will be adorable and somewhat inefficient."],
  ["surprise-064", "A little exhale", "You made it to this moment. Let yourself exhale before moving on to the next one."],
  ["surprise-065", "The missing spoon", "A spoon is missing. A Sipling has a new silver hat. We are choosing to celebrate resourcefulness."],
  ["surprise-066", "Ordinary magic", "A favorite mug can make an ordinary day feel a little more like home."],
  ["surprise-067", "A gentle blessing", "May peace meet you in the middle of your day, Marissa, wherever this little note finds you."],
  ["surprise-068", "The tiniest wave", "A tiny friend is waving with its whole body. It would really like you to know it’s happy you’re here."],
  ["surprise-069", "Enough for now", "You don’t need to solve the whole week in this moment. A little pause is enough for now."],
  ["surprise-070", "A happy little wobble", "Some Siplings walk. Some hop. One travels almost entirely by happy wobbling. All are making progress."],
  ["surprise-071", "The good mug", "Use the good mug, at least in your imagination. Today is a perfectly good reason."],
  ["surprise-072", "A quiet place to grow", "Roots do important work where nobody can see them. Quiet growth still matters."],
  ["surprise-073", "One lovely thought", "Here’s a thought to keep: your day can hold something good without being perfect."],
  ["surprise-074", "The cinnamon trail", "A Sipling followed a trail of cinnamon and found a pastry. We support this style of adventure."],
  ["surprise-075", "An unhurried hello", "Hello, Marissa. No task attached. Just a little hello from your café."],
  ["surprise-076", "Room for gratitude", "May one small thing invite a grateful smile today: a warm cup, a kind voice, a patch of sky."],
  ["surprise-077", "The honorary apron", "The Siplings have made you an honorary café apron. It has approximately seventeen pockets for tiny treasures."],
  ["surprise-078", "A soft little start", "Starting gently is still starting. You don’t have to burst into the day like an alarm clock."],
  ["surprise-079", "Cocoa wishes", "Sending you the feeling of warm cocoa held in both hands on a cool afternoon."],
  ["surprise-080", "The crumb detective", "A Sipling is investigating the missing biscuit. The crumbs on its face are, apparently, unrelated."],
  ["surprise-081", "A moment of trust", "May you find room to trust, rest, and take the next small step when you’re ready."],
  ["surprise-082", "Tiny treasures", "A smooth pebble. A pretty leaf. A happy memory. Little treasures don’t need to impress anyone."],
  ["surprise-083", "A seat beside the window", "Imagine rain on the window and nowhere you need to rush for just a minute."],
  ["surprise-084", "An excellent audience", "The Siplings would love to hear about your day. They may occasionally interrupt with an enthusiastic squeak."],
  ["surprise-085", "The slow bloom", "A flower doesn’t open faster because someone checks on it every five minutes. Be patient with your blooming."],
  ["surprise-086", "One warm thought", "May this note feel like someone saving you the warmest seat at the table."],
  ["surprise-087", "The cloud collector", "A Sipling has been collecting clouds that look like pastries. It calls this research."],
  ["surprise-088", "Peace in small pieces", "Peace doesn’t always arrive all at once. A quiet sip can be a little piece of it."],
  ["surprise-089", "A cheerful interruption", "This is a very small interruption to say: I hope something makes your eyes light up today."],
  ["surprise-090", "A heart-shaped leaf", "A Sipling found a heart-shaped leaf and immediately thought it belonged on your table."],
  ["surprise-091", "No perfect words needed", "You don’t need perfect words for reflection or prayer. There’s room for honesty and a little quiet."],
  ["surprise-092", "The pastry pillow", "Someone fell asleep on a pastry cushion. Thankfully, we checked before adding powdered sugar."],
  ["surprise-093", "The lovely middle", "You’re allowed to enjoy the middle of a story, before everything is figured out."],
  ["surprise-094", "A little sparkle left", "Even a tiring day can have one tiny sparkle in it. I hope yours is easy to find."],
  ["surprise-095", "A kind little voice", "Let the voice in your head borrow the gentleness you’d offer a sleepy little Sipling."],
  ["surprise-096", "Your café soundtrack", "Today’s café soundtrack features soft clinks, happy squeaks, and one Sipling humming completely off-key."],
  ["surprise-097", "A little open space", "May you find a moment today that belongs to you, without any hurry crowding into it."],
  ["surprise-098", "A brave little bud", "New things often begin as something small and a little uncertain. Buds don’t look like bouquets yet."],
  ["surprise-099", "The emergency cookie", "The café has an emergency imaginary cookie for moments that call for one. This can absolutely be one of those moments."],
  ["surprise-100", "An everyday blessing", "May ordinary comforts remind you that there is goodness worth noticing today."],
  ["surprise-101", "The ribbon problem", "A Sipling wrapped your note in a ribbon. Then it wrapped itself in the ribbon. Both are doing well."],
  ["surprise-102", "A little lightness", "I hope your next laugh arrives easily and leaves the day feeling a little lighter."],
  ["surprise-103", "The smallest welcome mat", "There’s a tiny welcome mat by the café door. Nobody can read it, but everyone agrees it feels friendly."],
  ["surprise-104", "Time for a sip", "A little pause between thoughts. A little warmth between hands. That’s the whole invitation."],
  ["surprise-105", "A quiet kind of lovely", "Some lovely things are quiet: a steady friendship, a gentle prayer, a moment when you feel at home."],
  ["surprise-106", "The coffee bean orchestra", "The Siplings started a band with coffee-bean shakers. Their rhythm is questionable. Their enthusiasm is spectacular."],
  ["surprise-107", "Little by little", "Small steps count even when they don’t make much noise. Especially when they’re taken in fluffy slippers."],
  ["surprise-108", "A place to return", "This café will still be cozy after a busy day away. You don’t have to catch up to belong here."],
  ["surprise-109", "The flowerpot resident", "A Sipling has moved into a flowerpot. It says the lighting is excellent and the neighbors are very leafy."],
  ["surprise-110", "A gentle hope for you", "May you meet today with a little hope and end it with something worth remembering."],
  ["surprise-111", "The kindness recipe", "The café’s secret recipe includes warmth, patience, and a generous helping of being glad you’re here."],
  ["surprise-112", "An imperfect heart", "A lopsided heart drawn with care is still a heart. Your imperfect efforts can hold a lot of love."],
  ["surprise-113", "A moment to notice", "Look for something small that you like about this moment. You can let that be enough."],
  ["surprise-114", "The pocket-sized picnic", "A Sipling packed a picnic in a bottle cap. You have been invited as the extremely large guest of honor."],
  ["surprise-115", "Your own little rhythm", "You can find a rhythm that feels like yours. The café is not keeping a stopwatch."],
  ["surprise-116", "A little prayer for peace", "May a moment of prayer bring you steadiness for whatever the rest of today holds."],
  ["surprise-117", "Good things ahead", "There are still coffees to enjoy, little friends to meet, and lovely moments you haven’t lived yet."],
  ["surprise-118", "The tiny librarian", "A Sipling is organizing the café books by how nice they are to nap beside. A thoughtful system, really."],
  ["surprise-119", "The softest assignment", "Your imaginary assignment is to picture a tiny creature wearing a sweater with sleeves that are much too long."],
  ["surprise-120", "A cozy corner of courage", "May you find both a soft place to rest and the courage for your next small adventure."],
  ["surprise-121", "The latte portrait", "A Sipling tried to draw your portrait in latte foam. You have become a very distinguished cloud."],
  ["surprise-122", "A little good company", "Whether your day is full of people or wonderfully quiet, I hope you feel the comfort of good company."],
  ["surprise-123", "More than a checklist", "You are more than the things you get done today, Marissa. There’s room here to simply enjoy being."],
  ["surprise-124", "The daisy delivery service", "Your flowers arrived by Sipling courier. Delivery was delayed by a butterfly, but the dedication was impressive."],
  ["surprise-125", "Little moments linger", "Sometimes a tiny happy moment stays with us longer than we expect. I hope this becomes one of yours."],
  ["surprise-126", "A gentle hand on the day", "You can hold today gently. It doesn’t need to be squeezed into something perfect."],
  ["surprise-127", "The sleepy greeting", "A very sleepy Sipling woke up just to say hello to you. It considers this an excellent use of its energy."],
  ["surprise-128", "A cup of possibility", "Imagine a fresh cup and a little possibility. You don’t have to decide what to do with either just yet."],
  ["surprise-129", "Space for stillness", "May a little stillness help you notice what your heart has been trying to say."],
  ["surprise-130", "The tiny umbrella", "A Sipling brought a cocktail umbrella in case your day feels rainy. Its practicality is limited; its concern is immense."],
  ["surprise-131", "A delightful discovery", "Somewhere, there’s a little thing you’ll love that you haven’t discovered yet. What a nice thought to carry."],
  ["surprise-132", "The muffin lookout", "A Sipling on a muffin-shaped cushion reports that everything is considerably cozier from up there."],
  ["surprise-133", "A little room for joy", "You’re allowed to make room for something that simply makes you happy."],
  ["surprise-134", "The gentle reset", "A day can have more than one fresh start. Maybe this sip is a small one."],
  ["surprise-135", "A hopeful little seed", "A hope doesn’t need to be big to be worth tending. Little seeds have their own quiet promise."],
  ["surprise-136", "The very serious bow", "A Sipling practiced a fancy bow to greet you. It tipped over, got up, and is extremely proud of the whole performance."],
  ["surprise-137", "Kindness in the details", "May someone remember a little detail that makes you feel seen today."],
  ["surprise-138", "A little comfort to carry", "Take the feeling of this cozy café with you, even if only for the length of one breath."],
  ["surprise-139", "The imaginary pastry case", "There is no wrong choice in the imaginary pastry case. A Sipling has volunteered to help with extensive research."],
  ["surprise-140", "A sweet little pause", "Let this be a small island of sweetness in the middle of whatever you’re doing."],
  ["surprise-141", "The sky outside", "I hope the sky gives you something pretty to look at today: a lovely cloud, a little color, a patch of stars."],
  ["surprise-142", "A soft place for questions", "You can bring your questions into your quiet moments of faith. You don’t have to arrive with every answer."],
  ["surprise-143", "The warm welcome club", "The warm welcome club has one rule: be very happy to see Marissa. Membership is flourishing."],
  ["surprise-144", "A little more gently", "Whatever you’re learning, you’re allowed to learn it gently. Even Siplings stumble over their own paws."],
  ["surprise-145", "The tea towel cape", "A Sipling is wearing a tea towel as a cape. Its superpower is making a very ordinary moment feel heroic."],
  ["surprise-146", "One small delight", "May a small delight find you today and stay long enough for you to notice."],
  ["surprise-147", "The cookie constellation", "The Siplings arranged chocolate chips into a constellation. It predicts an excellent chance of dessert."],
  ["surprise-148", "A quiet celebration", "Not every good thing needs a big announcement. You can smile quietly and keep a lovely moment for yourself."],
  ["surprise-149", "The bloom beside you", "A little flower is blooming by your imaginary table. It asks nothing of you except perhaps a passing smile."],
  ["surprise-150", "A tiny dose of wonder", "Consider the possibility of a creature so small it needs a ladder to peek into your mug. It would absolutely wave from the top."],
  ["surprise-151", "The cozy invitation", "Come in, settle down, and let your thoughts untangle a little. There’s no dress code except being yourself."],
  ["surprise-152", "A little steady light", "May your faith offer a steady light today, even in the ordinary spaces between the bigger moments."],
  ["surprise-153", "The tiny thank-you", "A Sipling made you a thank-you card for visiting. It used its best handwriting and several unnecessary stickers."],
  ["surprise-154", "A sip before the next thing", "Before the next thing asks for your attention, here’s one gentle moment just for you."],
  ["surprise-155", "The cheerful leaf boat", "A Sipling made a boat out of a leaf and sailed across a saucer. Adventure comes in all sizes."],
  ["surprise-156", "A little affection from the café", "This note contains no important updates. Just a little warmth and a very sincere imaginary hug."],
  ["surprise-157", "Room to be delighted", "It’s okay to be delighted by something small and silly. That is practically the founding principle of this café."],
  ["surprise-158", "The soft ending", "Whenever you’re ready to leave this little café, I hope you take a softer feeling with you."],
  ["surprise-159", "A hopeful pocket note", "May the rest of your day have room for a kind surprise, a deep breath, and something that makes you smile."],
  ["surprise-160", "Still glad you’re here", "If you’ve forgotten since the last note: this little café is still very glad you’re here, Marissa."],
].map(([id,title,message])=>({id,title,message}));
export function milestoneNote(progress: NoteProgress, seen: string[]): { note: LittleNote; covered: string[] } | null {
  const eligible = milestones.filter(n => progress[n.metric] >= n.at && !seen.includes(n.id));
  if (!eligible.length) return null;
  // Deliver one unlocked note at a time; pacing belongs to the UI scheduler.
  const note = eligible[eligible.length - 1];
  return { note, covered: [note.id] };
}
export function randomNote(seen: string[], random = Math.random): LittleNote {
  const fresh = surpriseNotes.filter(n => !seen.includes(n.id));
  const choices = fresh.length ? fresh : surpriseNotes.filter(n => n.id !== seen.at(-1));
  return choices[Math.min(choices.length - 1, Math.floor(random() * choices.length))];
}

export function rememberSurprise(seen: string[], id: string): string[] {
  const known = new Set(surpriseNotes.map(note => note.id));
  const history = [...new Set(seen.filter(value => known.has(value)))];
  // Start a fresh shuffled cycle after every surprise has had its turn.
  return history.length >= surpriseNotes.length ? [id] : [...history.filter(value => value !== id), id];
}
