export type NoteProgress = { coffees: number; friends: number; explorations: number; evolutions: number; care: number; games: number };
export type LittleNote = { id: string; title: string; message: string };
export const milestones: (LittleNote & { metric: keyof NoteProgress; at: number })[] = [
  { id:'coffee-1',metric:'coffees',at:1,title:'Your first little ritual',message:'A warm cup, a little pause, and a memory worth keeping. Here’s to many cozy moments, Marissa.' },
  { id:'coffee-10',metric:'coffees',at:10,title:'A cup full of memories',message:'Ten coffee moments tucked away. The ordinary little things can become the sweetest memories.' },
  { id:'coffee-30',metric:'coffees',at:30,title:'Your cozy corner is growing',message:'Thirty little pauses. I hope this café keeps giving you a soft place to land, Marissa.' },
  { id:'friends-5',metric:'friends',at:5,title:'A tiny welcoming committee',message:'Five Siplings have found their way to you. They’ve clearly heard you’re excellent company.' },
  { id:'friends-25',metric:'friends',at:25,title:'Quite the little gathering',message:'Twenty-five friends! Someone should probably put another pot of coffee on.' },
  { id:'friends-100',metric:'friends',at:100,title:'A hundred little wonders',message:'A hundred Siplings, and still so much wonder ahead. Your curiosity makes this little world come alive.' },
  { id:'friends-300',metric:'friends',at:300,title:'Look at all this wonder',message:'Three hundred friends. Somewhere in this café, a tiny Sipling is trying to organize a very large group hug.' },
  { id:'friends-600',metric:'friends',at:600,title:'Every little friend, found',message:'All six hundred Siplings are home. What a beautiful little world you’ve made, Marissa.' },
  { id:'explore-1',metric:'explorations',at:1,title:'A little brave beginning',message:'One small adventure can lead to something lovely. I’m glad you took that first step, Marissa.' },
  { id:'explore-20',metric:'explorations',at:20,title:'A heart for adventure',message:'Twenty adventures later, there’s still magic around the next corner. Take your curiosity with you.' },
  { id:'evolve-1',metric:'evolutions',at:1,title:'Small beginnings, big wonder',message:'That tiny friend had something magnificent inside all along. Growing into something new takes a little care.' },
  { id:'evolve-10',metric:'evolutions',at:10,title:'Look how far they’ve grown',message:'Ten transformations, each its own kind of wonderful. Thank you for giving little things room to grow.' },
  { id:'care-5',metric:'care',at:5,title:'Kindness looks good on you',message:'Five little acts of care. Your Siplings appreciate every one—and probably have a few crumbs on their faces to prove it.' },
  { id:'game-1',metric:'games',at:1,title:'A tiny victory dance',message:'Your first memory-game win deserves a happy little wiggle. The Siplings are already doing theirs.' },
  {"id": "coffee-3", "metric": "coffees", "at": 3, "title": "Three cozy moments", "message": "Three cups remembered, three little pauses made yours. The café is learning your kind of cozy."},
  {"id": "coffee-5", "metric": "coffees", "at": 5, "title": "Your favorite little ritual", "message": "Five coffee memories! A Sipling is preparing a loyalty card with a paw print in every square."},
  {"id": "coffee-20", "metric": "coffees", "at": 20, "title": "Twenty sips of your story", "message": "Twenty coffee moments saved. May there be a happy little memory tucked into your next cup too."},
  {"id": "coffee-50", "metric": "coffees", "at": 50, "title": "Fifty warm little pauses", "message": "Fifty coffee memories belong to this café now. That is a lovely collection of ordinary moments, Marissa."},
  {"id": "coffee-100", "metric": "coffees", "at": 100, "title": "A hundred cups of cozy", "message": "One hundred coffee moments! The imaginary barista is polishing your very special imaginary mug."},
  {"id": "friends-10", "metric": "friends", "at": 10, "title": "Ten tiny personalities", "message": "Ten Siplings have joined your world. The group photo includes at least one enthusiastic blur."},
  {"id": "friends-50", "metric": "friends", "at": 50, "title": "A wonderfully full table", "message": "Fifty friends! Someone has started a seating chart. Someone else has eaten the corner of it."},
  {"id": "friends-150", "metric": "friends", "at": 150, "title": "So many little hellos", "message": "A hundred and fifty Siplings found. That is a lot of tiny faces happy to see you."},
  {"id": "friends-200", "metric": "friends", "at": 200, "title": "A whole neighborhood of wonder", "message": "Two hundred little friends! Your café is beginning to need its own very small town square."},
  {"id": "friends-400", "metric": "friends", "at": 400, "title": "Four hundred reasons to smile", "message": "Four hundred Siplings! Every little face adds something different to the world you’re discovering."},
  {"id": "friends-500", "metric": "friends", "at": 500, "title": "An extraordinary gathering", "message": "Five hundred friends found. The welcome party now requires several cakes and a rather ambitious banner."},
  {"id": "explore-5", "metric": "explorations", "at": 5, "title": "Getting your paws dusty", "message": "Five adventures! A little dust on your shoes and a little more wonder in your world."},
  {"id": "explore-10", "metric": "explorations", "at": 10, "title": "A happy little wanderer", "message": "Ten trips into the unknown. Your curiosity has excellent taste in adventures."},
  {"id": "explore-50", "metric": "explorations", "at": 50, "title": "Fifty paths wandered", "message": "Fifty adventures behind you. I hope the next little trail holds something that makes you grin."},
  {"id": "explore-100", "metric": "explorations", "at": 100, "title": "A well-traveled heart", "message": "One hundred explorations! Your imaginary travel journal is full of paw prints and very excited punctuation."},
  {"id": "explore-250", "metric": "explorations", "at": 250, "title": "A world you keep discovering", "message": "Two hundred and fifty adventures. There is something lovely about continuing to look for wonder."},
  {"id": "evolve-3", "metric": "evolutions", "at": 3, "title": "A little growing circle", "message": "Three evolutions! Tiny beginnings keep turning into magnificent surprises around here."},
  {"id": "evolve-5", "metric": "evolutions", "at": 5, "title": "Five wonderful transformations", "message": "Five Siplings have grown into new forms. Some of them may now need a larger café chair."},
  {"id": "evolve-25", "metric": "evolutions", "at": 25, "title": "From tiny paws to mighty friends", "message": "Twenty-five evolutions. Your café contains an impressive amount of power and an equally impressive need for snacks."},
  {"id": "evolve-50", "metric": "evolutions", "at": 50, "title": "Magnificent things take care", "message": "Fifty transformations! All that growing has made this little world wonderfully unexpected."},
  {"id": "care-15", "metric": "care", "at": 15, "title": "A little kindness adds up", "message": "Fifteen acts of care. Small kindnesses are becoming a lovely habit in your café."},
  {"id": "care-50", "metric": "care", "at": 50, "title": "A café full of care", "message": "Fifty caring moments! Your Siplings would like to return the favor with a slightly chaotic cuddle pile."},
  {"id": "care-100", "metric": "care", "at": 100, "title": "A hundred gentle gestures", "message": "One hundred acts of care. Every little friend deserves to feel looked after, and so do you, Marissa."},
  {"id": "game-5", "metric": "games", "at": 5, "title": "Five happy victory wiggles", "message": "Five memory-game wins! The Siplings are developing a victory dance with far too many spins."},
  {"id": "game-15", "metric": "games", "at": 15, "title": "A lovely little winning collection", "message": "Fifteen memory-game wins. Your tiny cheering section has worn out one set of imaginary pom-poms."},
  {"id": "game-50", "metric": "games", "at": 50, "title": "Fifty reasons for confetti", "message": "Fifty memory-game wins! The café is celebrating with petal confetti and a well-deserved imaginary cookie."},
];
export const surpriseNotes: LittleNote[] = [
  ['made-for-you','Just for you, Marissa','This little world was made to bring you a smile. I hope it finds you at just the right moment.'],
  ['warmth','A pocket of warmth','May your coffee be lovely, your shoulders feel lighter, and your day have a little unexpected goodness in it.'],
  ['bean','An important café update','A Sipling has appointed itself your official cheerleader. It is very small, very determined, and entirely on your side.'],
  ['rest','Permission to pause','You don’t have to earn a quiet moment. Take a breath, settle in, and let this one be yours.'],
  ['faith','A gentle wish','May you feel loved and held today, Marissa. There is room here for your hopes, your prayers, and your quiet moments.'],
  ['tiny','Something lovely','A little kindness. A warm mug. A very round Sipling. Sometimes joy arrives in the smallest packages.'],
  ['enough','For an ordinary day','You don’t have to make today extraordinary to find something beautiful in it.'],
  ['coffee','The café is on your side','Your imaginary coffee is always the perfect temperature. Your tiny friends are always happy you’re here.'],
  ['wonder','Keep a little wonder','I hope something makes you smile today—the kind of smile that sneaks up on you.'],
  ['grace','A little grace','Some days bloom slowly. Be gentle with yourself while yours unfolds.'],
  ['welcome','A familiar little place','Welcome back to your soft little corner of the world, Marissa. There’s always a place for you here.'],
  ['secret','A tiny secret','The Siplings held a meeting. The agenda was snacks. They also agreed that you’re pretty wonderful.'],
  ["surprise-013", "A small delivery", "A Sipling left a tiny flower by your cup. It took three trips to carry it, so please act surprised."],
  ["surprise-014", "Foam forecast", "Today’s forecast: a chance of fluffy clouds, warm coffee, and one extremely enthusiastic little friend."],
  ["surprise-015", "Reserved seating", "The comfiest chair in the café has your name on it, Marissa. The Siplings checked twice."],
  ["surprise-016", "Pocket sunshine", "Here’s a little sunshine for your pocket. Save it for a moment that could use some warmth."],
  ["surprise-017", "The biscuit committee", "The biscuit committee would like you to know that broken cookies still count as excellent cookies."],
  ["surprise-018", "Soft landing", "Whatever kind of day brought you here, you can set it down for a little while."],
  ["surprise-019", "A very small parade", "A parade in your honor is forming behind the sugar bowl. Progress is slow. Everyone has tiny legs."],
  ["surprise-020", "No rush, lovely", "Your cup doesn’t have a deadline. Neither does this little moment of peace."],
  ["surprise-021", "Window seat wishes", "May your next quiet moment feel like sunshine through a café window."],
  ["surprise-022", "The official verdict", "The Siplings reviewed the evidence. You deserve something nice today. Their report includes a doodle of a heart."],
  ["surprise-023", "Tiny paws, big plans", "Someone with very tiny paws is planning to make your day better. Step one appears to be waving at you."],
  ["surprise-024", "A little room to breathe", "Let your shoulders fall a little. There you go. There’s room to breathe here."],
  ["surprise-025", "Extra sweetness", "Your imaginary barista added an extra sprinkle of kindness. It’s the house specialty."],
  ["surprise-026", "A soft reminder", "Marissa, you’re allowed to enjoy a good moment without figuring out what comes next."],
  ["surprise-027", "A flower for your thoughts", "If your thoughts are busy, picture a little flower growing beside them. It doesn’t need to hurry either."],
  ["surprise-028", "The napkin artist", "A Sipling drew you a masterpiece on a napkin. It might be a heart. It might be a potato. The affection is clear."],
  ["surprise-029", "A lovely little detour", "Sometimes the best part of the day is the small, happy detour you didn’t plan."],
  ["surprise-030", "Steeped in kindness", "May a little kindness find its way into everything you do today, including how you speak to yourself."],
  ["surprise-031", "Your tiny fan club", "Your fan club has assembled. Attendance is excellent. One member fell asleep in a teacup."],
  ["surprise-032", "Nothing to prove", "You can simply be Marissa here. That’s more than enough for this little café."],
  ["surprise-033", "A quiet amen", "May a quiet moment of prayer leave a little more peace in your heart today."],
  ["surprise-034", "The marshmallow incident", "A Sipling tried to hug a marshmallow. We have decided this counts as a perfectly reasonable afternoon."],
  ["surprise-035", "Take the scenic sip", "There’s no prize for finishing your imaginary coffee quickly. Take the scenic sip."],
  ["surprise-036", "A tiny bouquet", "Someone gathered a bouquet just for you. It contains a daisy, a leaf, and a very promising twig."],
  ["surprise-037", "Goodness can be small", "A kind word can be small enough to fit in a moment and still stay with you all day."],
  ["surprise-038", "A cozy plot twist", "Perhaps something lovely is waiting in a part of today you haven’t reached yet."],
  ["surprise-039", "Little lantern", "May your faith be a little lantern when the path ahead feels hard to see."],
  ["surprise-040", "The sugar bowl lookout", "A Sipling is watching for your smile from the sugar bowl. It has packed snacks for the mission."],
  ["surprise-041", "Gentle company", "You don’t need to fill the silence. Sometimes gentle company is enough."],
  ["surprise-042", "A tiny toast", "Here’s to warm mugs, good company, and remembering where you put your coffee before it gets cold."],
  ["surprise-043", "The blanket inspector", "A very serious Sipling has inspected the café blankets. Its professional recommendation is to get cozy."],
  ["surprise-044", "A place for your hopes", "Bring your hopes, even the ones you don’t have words for yet. There’s space for them here."],
  ["surprise-045", "Sprinkles of joy", "If joy came in a shaker, the Siplings would absolutely forget to put the lid back on."],
  ["surprise-046", "A bright little thing", "I hope you notice one bright little thing today and let yourself enjoy it fully."],
  ["surprise-047", "Rest is welcome", "Even the café’s most adventurous Sipling takes naps. Sometimes right in the middle of an important sentence."],
  ["surprise-048", "A heart at ease", "May your heart find a little ease between everything you’re carrying today."],
  ["surprise-049", "A sip of silliness", "A Sipling ordered a cappuccino the size of its entire body. We admire the ambition."],
  ["surprise-050", "Come as you are", "Messy day or lovely day, you can come as you are. The café doesn’t require a polished entrance."],
  ["surprise-051", "A prayer-sized pause", "A breath, a hope, a few honest words. Your quiet moments of faith can be simple."],
  ["surprise-052", "Tiny applause", "If you hear a faint pattering, that’s the Siplings applauding you with their very small paws."],
  ["surprise-053", "The cozy department", "The cozy department has approved an extra moment of doing absolutely nothing."],
  ["surprise-054", "A little courage", "You don’t have to feel fearless to take a small step. Tiny paws take brave steps too."],
  ["surprise-055", "Your table is ready", "Marissa, your table is ready. The flowers are slightly crooked because a Sipling arranged them with great enthusiasm."],
  ["surprise-056", "A pleasant surprise", "May something sweet catch you off guard today, like finding a cookie you forgot you saved."],
  ["surprise-057", "Moonlight manners", "The moon doesn’t rush to be full. You can let your own growing take its time."],
  ["surprise-058", "A fragrant little thought", "Imagine the smell of fresh coffee and a warm pastry. That’s the mood this note is trying to bring you."],
  ["surprise-059", "A little kindness returned", "I hope some of the kindness you put into the world finds its way back to you today."],
  ["surprise-060", "A very fluffy assistant", "Your fluffy assistant is ready to help. It can offer moral support and sit on exactly the paper you need."],
  ["dad-joke-01", "Espresso yourself", "Why did the coffee start a journal? It had a latte feelings to espresso."],
  ["christian-faith-01", "Loved before the checklist", "Marissa, God’s love is not a prize for getting everything right today. You can come to Him just as you are."],
  ["dad-joke-02", "A latte affection", "What did one coffee say to the other? You mean a latte to me."],
  ["christian-faith-02", "A little prayer together", "Lord Jesus, help us notice Your goodness in ordinary moments and share Your kindness with the people we meet. Amen."],
  ["dad-joke-03", "Bean thinking", "Why did the coffee send a postcard? It had bean thinking of you."],
  ["christian-faith-03", "Grace for today", "May the grace of Jesus meet you in the parts of today that feel unfinished. You don’t have to hide them from Him."],
  ["dad-joke-04", "Grounded advice", "Why was the coffee so sensible? It stayed grounded."],
  ["christian-faith-04", "A quiet place with God", "You can bring God your honest thoughts, even when they come out as a sigh instead of a carefully worded prayer."],
  ["dad-joke-05", "The shy cup", "Why did the mug blush? Someone called it brew-tiful."],
  ["christian-faith-05", "Our shared hope", "May our shared faith in Christ keep teaching us to love with patience, speak with kindness, and make room for grace."],
  ["dad-joke-06", "A cozy mystery", "Who stole the café’s cookies? We’re following the crumb trail."],
  ["christian-faith-06", "A morning mercy", "A new day is a lovely invitation to turn toward God again. Yesterday doesn’t need to have the last word."],
  ["dad-joke-07", "A little musical talent", "What do you call a musical pastry? A cinnamon roll model."],
  ["christian-faith-07", "Rest with Jesus", "When your heart feels busy, take a quiet moment with Jesus. You don’t need an impressive prayer to draw near."],
  ["dad-joke-08", "The muffin question", "What did the muffin say when it was invited along? I’m up for muffin much!"],
  ["christian-faith-08", "A prayer for your heart", "Heavenly Father, give Marissa peace for this moment, wisdom for her choices, and reminders of Your love today. Amen."],
  ["dad-joke-09", "A toast to you", "Why did the bread give a speech? It wanted to make a toast."],
  ["christian-faith-09", "Small acts of love", "Following Jesus can look like an ordinary kindness: listening well, forgiving gently, or making someone feel welcome."],
  ["dad-joke-10", "One smart cookie", "Why did the cookie go to school? To become a smart cookie."],
  ["christian-faith-10", "Room for gratitude", "Before the next sip, consider one thing you can thank God for. It can be as small as the warmth of the cup."],
  ["dad-joke-11", "The pastry workout", "How does a croissant stay in shape? Butter stretches."],
  ["christian-faith-11", "Held in prayer", "May this little note remind you that your hopes and worries belong in prayer, not only the things you think sound important."],
  ["dad-joke-12", "A tiny dough joke", "Why did the baker need a nap? They were feeling a little kneady."],
  ["christian-faith-12", "A steady hope", "Our hope in Jesus reaches beyond how smoothly a day goes. A difficult afternoon doesn’t mean you have been forgotten."],
  ["dad-joke-13", "The sleepy dinosaur", "What do you call a sleeping dinosaur? A dino-snore."],
  ["christian-faith-13", "Love with patience", "Lord, help us be patient with one another today. Teach us to love in the small moments, where so much of life happens. Amen."],
  ["dad-joke-14", "A helpful dinosaur", "What do you call a dinosaur with a big vocabulary? A thesaurus."],
  ["christian-faith-14", "A little courage from faith", "You can ask God for courage without pretending you aren’t nervous. Honest faith has room for a trembling first step."],
  ["dad-joke-15", "The polite ocean", "What did the ocean say to the shore? Nothing. It just waved."],
  ["christian-faith-15", "A gentle return", "If your thoughts wander during prayer, you can gently return. Time with God isn’t a performance you have to perfect."],
  ["dad-joke-16", "A tree’s best friend", "How do trees get online? They log in."],
  ["christian-faith-16", "Peace at the table", "May this little café pause become a moment to remember Christ’s peace and breathe a little more slowly."],
  ["dad-joke-17", "A leafy compliment", "Why are trees so good at friendship? They always branch out."],
  ["christian-faith-17", "A prayer for kindness", "Jesus, let our words leave people feeling cared for. Help us choose gentleness when it would be easier to be sharp. Amen."],
  ["dad-joke-18", "The mushroom invitation", "Why did the mushroom get invited to the café? Because it was a fungi."],
  ["christian-faith-18", "Seen by God", "Marissa, the quiet good you do matters even when it draws no applause. You can offer it to God with love."],
  ["dad-joke-19", "A tiny fish joke", "What do you call a fish wearing a bow tie? Sofishticated."],
  ["christian-faith-19", "Faith in the ordinary", "God is not only someone to turn to in the biggest moments. There is room for Him in errands, coffee breaks, and ordinary Tuesdays."],
  ["dad-joke-20", "A chilly puppy", "What do you call a dog in the snow? A chili dog."],
  ["christian-faith-20", "A grateful little heart", "Lord, thank You for small joys, warm company, and the chance to begin again. Help us receive today with gratitude. Amen."],
  ["dad-joke-21", "A fluffy instrument", "What’s a sheep’s favorite instrument? The baa-ssoon."],
  ["christian-faith-21", "Grace to grow", "Growing in Christ is a journey. You can learn, ask questions, and begin again without demanding instant perfection from yourself."],
  ["dad-joke-22", "A very fancy bee", "How does a bee brush its hair? With a honeycomb."],
  ["christian-faith-22", "A moment to listen", "You don’t have to fill every quiet moment with words. Make a little room to be still before God today."],
  ["dad-joke-23", "The bee’s hairstyle", "What kind of haircut does a bee get? A buzz cut."],
  ["christian-faith-23", "Our little prayer", "Father, help our faith grow deeper and our love become more thoughtful. Let our ordinary days make room for You. Amen."],
  ["dad-joke-24", "The penguin café", "What does a penguin order at the café? An ice coffee."],
  ["christian-faith-24", "When plans change", "Changed plans can be frustrating. You can bring that frustration to God and ask for wisdom for the next step."],
  ["dad-joke-25", "The bear’s order", "Why did the bear skip dessert? It was already stuffed."],
  ["christian-faith-25", "A kind word counts", "A gentle word can be a small way of reflecting Jesus’ love. May one find its way to you today, too."],
  ["dad-joke-26", "A dramatic duck", "Why did the duck bring a suitcase? It was ready to quack on with its travels."],
  ["christian-faith-26", "A prayer for rest", "Lord Jesus, help Marissa set down what she cannot solve in this moment and receive a little rest in Your care. Amen."],
  ["dad-joke-27", "A sleepy bicycle", "Why did the bicycle take a nap? It was two-tired."],
  ["christian-faith-27", "Hope beyond the weather", "A cloudy mood doesn’t cancel your faith. You can turn toward Jesus on the bright days and the gray ones."],
  ["dad-joke-28", "The calendar’s worries", "Why was the calendar nervous? Its days were numbered."],
  ["christian-faith-28", "A faithful little step", "You don’t need to see every step ahead to ask God for help with the one in front of you."],
  ["dad-joke-29", "A musical ladder", "Why did the musician bring a ladder? To reach the high notes."],
  ["christian-faith-29", "Love that listens", "May our faith make us better listeners: slower to assume, quicker to understand, and willing to care in practical ways."],
  ["dad-joke-30", "A bright idea", "Why did the lamp get invited to dinner? It always brightened the room."],
  ["christian-faith-30", "A prayer before adventure", "God, give us curious hearts, wise choices, and eyes that notice the beauty of Your creation. Amen."],
  ["dad-joke-31", "The shy tomato", "Why did the tomato blush? It saw the salad dressing."],
  ["christian-faith-31", "Wonder in creation", "A flower, a patch of sunlight, a sky full of stars—may something in God’s creation invite you into wonder today."],
  ["dad-joke-32", "A berry sweet thought", "What did the strawberry say to Marissa? I like you berry much."],
  ["christian-faith-32", "A little forgiveness", "Jesus teaches us to forgive. If that feels difficult today, you can begin by asking Him for help, one honest prayer at a time."],
  ["dad-joke-33", "The banana appointment", "Why did the banana visit the doctor? It wasn’t peeling well."],
  ["christian-faith-33", "Thankful for you", "This café has room for a simple prayer of gratitude: thank You, God, for Marissa and the joy of sharing life’s little moments."],
  ["dad-joke-34", "A grape attitude", "What did the grape say when life got busy? I’m raisin my spirits."],
  ["christian-faith-34", "An honest conversation", "Prayer can begin with, “God, here’s what is on my heart.” You don’t need to dress it up before bringing it to Him."],
  ["dad-joke-35", "An egg-cellent entrance", "How does an egg greet its friends? With an egg-stra big hello."],
  ["christian-faith-35", "A prayer for wisdom", "Father, give Marissa wisdom for what needs a decision, patience for what needs time, and peace for what can wait. Amen."],
  ["dad-joke-36", "A cheesier note", "What cheese can never be yours? Nacho cheese."],
  ["christian-faith-36", "Faith with open hands", "May we learn to bring our plans to God with open hands, asking for His guidance while taking the steps we can."],
  ["dad-joke-37", "The noodle mystery", "What do you call a fake noodle? An impasta."],
  ["christian-faith-37", "A little light to share", "You don’t have to brighten the whole world today. A small act of Christlike love can matter to the person in front of you."],
  ["dad-joke-38", "The potato photographer", "What did the potato say for the photo? Eyes over here!"],
  ["christian-faith-38", "A prayer for joy", "Jesus, help us receive good things with grateful hearts. Let our joy make us generous with encouragement and kindness. Amen."],
  ["dad-joke-39", "A good little book", "Why did the book join the café? It wanted to turn over a new leaf."],
  ["christian-faith-39", "Loved on the quiet days", "Your worth before God is not measured by how productive, cheerful, or impressive you feel today."],
  ["dad-joke-40", "A pencil’s confidence", "Why did the pencil feel prepared? It had a point."],
  ["christian-faith-40", "Together in grace", "May our Christian faith give us a shared place to return: to prayer, to forgiveness, and to the love Jesus teaches us."],
  ["dad-joke-41", "The wandering clock", "Why did the clock go for a walk? It had time on its hands."],
  ["christian-faith-41", "A small invitation", "If you have a quiet minute, spend it with God. A little prayer can fit between sips of coffee."],
  ["dad-joke-42", "A tiny construction joke", "Want to hear a construction joke? I’m still working on it."],
  ["christian-faith-42", "A prayer for others", "Lord, bring to mind someone who could use encouragement today, and help us show them care in a simple, thoughtful way. Amen."],
  ["dad-joke-43", "The invisible joke", "Want to hear a joke about paper? Never mind. It’s tearable."],
  ["christian-faith-43", "A heart that serves", "Serving others doesn’t always look grand. Sometimes it looks like making room, lending a hand, or remembering what matters to someone."],
  ["dad-joke-44", "A cheesy pizza joke", "I made a joke about pizza, but it’s a little cheesy. The Siplings still want a slice."],
  ["christian-faith-44", "Christ at the center", "May we keep making room for Jesus in how we love, how we forgive, and how we choose to spend our ordinary days."],
  ["dad-joke-45", "The Sipling’s luggage", "Why did the Sipling pack a spoon? It was going on a stirring adventure."],
  ["christian-faith-45", "A prayer when tired", "God, You know when our strength feels small. Help us receive support, take wise rest, and walk through today with You. Amen."],
  ["dad-joke-46", "A tiny café superhero", "What’s a barista’s superpower? The ability to espresso themselves under pressure."],
  ["christian-faith-46", "A little trust", "You don’t need to pretend you understand everything to trust God. You can bring Him the questions along with the hope."],
  ["dad-joke-47", "The plant’s happy place", "Why did the plant love the café window? It was rooting for a sunny day."],
  ["christian-faith-47", "A thankful pause", "Thank You, Lord, for laughter, for comfort, and for the people who make a day feel warmer. Help us treasure them well. Amen."],
  ["dad-joke-48", "A lovely pear", "What did one pear say to the other? We make a great pear."],
  ["christian-faith-48", "A gentle witness", "May the way we treat people reflect the love we believe in: thoughtful, patient, and willing to show up."],
  ["dad-joke-49", "The cookie’s scarf", "Why did the cookie wear a scarf? It felt a little crumby in the cold."],
  ["christian-faith-49", "A prayer for tomorrow", "Father, help us care for what is ours to do today and bring tomorrow’s worries to You in prayer. Amen."],
  ["dad-joke-50", "A coffee farewell", "What did the coffee say before its adventure? See you on the flip sip!"],
  ["christian-faith-50", "A blessing for this moment", "Marissa, may you know the comfort of Christ’s love, the steadiness of hope, and the joy of a little goodness today."],
].map(([id,title,message])=>({id,title,message}));
export function milestoneNote(progress: NoteProgress, seen: string[]): { note: LittleNote; covered: string[] } | null {
  const eligible = milestones.filter(n => progress[n.metric] >= n.at && !seen.includes(n.id));
  if (!eligible.length) return null;
  // Deliver one unlocked note at a time; pacing belongs to the UI scheduler.
  const note = eligible[eligible.length - 1];
  return { note, covered: [note.id] };
}
export function randomNote(seen: string[], random = Math.random): LittleNote {
  const fresh = surpriseNotes.filter(n => !seen.includes(n.id));
  const choices = fresh.length ? fresh : surpriseNotes.filter(n => n.id !== seen.at(-1));
  return choices[Math.min(choices.length - 1, Math.floor(random() * choices.length))];
}

export function rememberSurprise(seen: string[], id: string): string[] {
  const known = new Set(surpriseNotes.map(note => note.id));
  const history = [...new Set(seen.filter(value => known.has(value)))];
  // Start a fresh shuffled cycle after every surprise has had its turn.
  return history.length >= surpriseNotes.length ? [id] : [...history.filter(value => value !== id), id];
}
